In [1]:
import pandas as pd
from scipy.sparse import coo_matrix,csr_matrix

# import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

import pickle
from function import *
from sklearn.model_selection import train_test_split

from implicit.als import AlternatingLeastSquares
from implicit.evaluation import mean_average_precision_at_k

In [2]:
import os
import threadpoolctl

os.environ['MKL_NUM_THREADS'] = '1'
os.environ['OPENBLAS_NUM_THREADS'] = '1'
os.environ['OMP_NUM_THREADS'] = '1'

threadpoolctl.threadpool_limits(3, "blas")

In [3]:
# # # Производим десериализацию и извлекаем из файла формата pkl
with open('data/events.pkl', 'rb') as pkl_file:
    events = pickle.load(pkl_file)

with open('data/category_tree.pkl', 'rb') as pkl_file:
    category_tree = pickle.load(pkl_file)

with open('data/item_properties.pkl', 'rb') as pkl_file:
    item_properties = pickle.load(pkl_file)

In [4]:
display(events.head(3))
display(category_tree.head(3))
display(item_properties.head(3))

,timestamp,visitorid,event,itemid,transactionid,day_of_week,year,month,day,hour,minute,part_day,Day Period
0,2015-06-02 05:02:12.117,257597,view,355908,NaN,1,2015,6,2,5,2,Morning,Dawn
1,2015-06-02 05:50:14.164,992329,view,248676,NaN,1,2015,6,2,5,50,Morning,Dawn
2,2015-06-02 05:13:19.827,111016,view,318965,NaN,1,2015,6,2,5,13,Morning,Dawn

   categoryid  parentid
0        1016     213.0
1         809     169.0
2         570       9.0

    timestamp  itemid    property                            value
0  2015-06-28  460429  categoryid                             1338
1  2015-09-06  206783         888          1116713 960601 n277.200
2  2015-08-09  395014         400  n552.000 639502 n720.000 424566

In [5]:
events['timestamp'] = pd.to_datetime(events['timestamp'])
item_properties['timestamp'] = pd.to_datetime(item_properties['timestamp'])

In [6]:
events.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2755641 entries, 0 to 2756100
Data columns (total 13 columns):
 #   Column         Dtype
---  ------         -----
 0   timestamp      datetime64[ns]
 1   visitorid      int64
 2   event          object
 3   itemid         int64
 4   transactionid  float64
 5   day_of_week    int32
 6   year           int32
 7   month          int32
 8   day            int32
 9   hour           int32
 10  minute         int32
 11  part_day       object
 12  Day Period     object
dtypes: datetime64[ns](1), float64(1), int32(6), int64(2), object(3)
memory usage: 231.3+ MB

In [7]:
category_tree.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1669 entries, 0 to 1668
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   categoryid  1669 non-null   int64
 1   parentid    1644 non-null   float64
dtypes: float64(1), int64(1)
memory usage: 26.2 KB

In [8]:
item_properties.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20275902 entries, 0 to 20275901
Data columns (total 4 columns):
 #   Column     Dtype
---  ------     -----
 0   timestamp  datetime64[ns]
 1   itemid     int64
 2   property   object
 3   value      object
dtypes: datetime64[ns](1), int64(1), object(2)
memory usage: 618.8+ MB

# Исследование данных

### Описание структуры данных  
### Статистический анализ данных

Типы событий array(['view', 'addtocart', 'transaction'], dtype=object)  
Проверим, что деньги списываются, только при проведении транзакции, а при просмотре или добавлении товара в корзину.

In [9]:
events[events['event']!='transaction']['transactionid'].unique()

array([nan])

In [10]:
events.describe(include='all')

,timestamp,visitorid,event,itemid,transactionid,day_of_week,year,month,day,hour,minute,part_day,Day Period
count,2755641,2.755641e+06,2755641,2.755641e+06,22457.000000,2.755641e+06,2755641.0,2.755641e+06,2.755641e+06,2.755641e+06,2.755641e+06,2755641,2755641
unique,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,5
top,NaN,NaN,view,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Evening,Evening
freq,NaN,NaN,2664218,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1092194,1078018
mean,2015-07-09 06:46:18.779006720,7.019227e+05,NaN,2.349214e+05,8826.497796,2.763684e+00,2015.0,6.771041e+00,1.539001e+01,1.279448e+01,2.969774e+01,NaN,NaN
min,2015-05-03 03:00:04.384000,0.000000e+00,NaN,3.000000e+00,0.000000,0.000000e+00,2015.0,5.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,NaN,NaN
25%,2015-06-05 04:21:34.039000064,3.505660e+05,NaN,1.181200e+05,4411.000000,1.000000e+00,2015.0,6.000000e+00,8.000000e+00,4.000000e+00,1.500000e+01,NaN,NaN
50%,2015-07-09 14:39:51.604000,7.020600e+05,NaN,2.360620e+05,8813.000000,3.000000e+00,2015.0,7.000000e+00,1.500000e+01,1.600000e+01,3.000000e+01,NaN,NaN
75%,2015-08-10 16:44:03.217999872,1.053443e+06,NaN,3.507140e+05,13224.000000,4.000000e+00,2015.0,8.000000e+00,2.300000e+01,2.000000e+01,4.500000e+01,NaN,NaN
max,2015-09-18 02:59:47.788000,1.407579e+06,NaN,4.668670e+05,17671.000000,6.000000e+00,2015.0,9.000000e+00,3.100000e+01,2.300000e+01,5.900000e+01,NaN,NaN
std,NaN,4.056892e+05,NaN,1.341947e+05,5098.996290,1.964294e+00,0.0,1.291462e+00,8.667116e+00,7.867576e+00,1.733139e+01,NaN,NaN

In [11]:
# fig = make_subplots(rows=7, cols=3,
#                     subplot_titles=['transactionid, event = transaction', 'transactionid, event = addtocart','transactionid, event = view',
#                                     'hour, event = transaction','hour, event = addtocart','hour, event = view',
#                                     'day_of_week, event = transaction','day_of_week, event = addtocart','day_of_week, event = view',
#                                     'month, event = transaction','month, event = addtocart','month, event = view',
#                                     'day, event = transaction','day, event = addtocart','day, event = view',
#                                     'part_day, event = transaction','part_day, event = addtocart','part_day, event = view',
#                                     'Day Period, event = transaction','Day Period, event = addtocart','Day Period, event = addtocart'
#                                     ])

# trace00 = go.Histogram(x=events[events['event']=='transaction']['transactionid'],orientation='v',name='transactionid',)
# trace01 = go.Histogram(x=events[events['event']=='transaction']['hour'],orientation='v',name='hour',)
# trace02 = go.Histogram(x=events[events['event']=='transaction']['day_of_week'],orientation='v',name='day_of_week',)
# trace03 = go.Histogram(x=events[events['event']=='transaction']['month'],orientation='v',name='month',)
# trace04 = go.Histogram(x=events[events['event']=='transaction']['day'],orientation='v',name='day',)
# trace05 = go.Histogram(x=events[events['event']=='transaction']['part_day'],orientation='v',name='part_day',)
# trace06 = go.Histogram(x=events[events['event']=='transaction']['Day Period'],orientation='v',name='part_day',)

# trace07 = go.Histogram(x=events[events['event']=='addtocart']['transactionid'],orientation='v',name='transactionid',)
# trace08 = go.Histogram(x=events[events['event']=='addtocart']['hour'],orientation='v',name='hour',)
# trace09 = go.Histogram(x=events[events['event']=='addtocart']['day_of_week'],orientation='v',name='day_of_week',)
# trace10 = go.Histogram(x=events[events['event']=='addtocart']['month'],orientation='v',name='month',)
# trace11 = go.Histogram(x=events[events['event']=='addtocart']['day'],orientation='v',name='day',)
# trace12 = go.Histogram(x=events[events['event']=='addtocart']['part_day'],orientation='v',name='part_day',)
# trace13 = go.Histogram(x=events[events['event']=='transaction']['Day Period'],orientation='v',name='part_day',)

# trace14 = go.Histogram(x=events[events['event']=='view']['transactionid'],orientation='v',name='transactionid',)
# trace15 = go.Histogram(x=events[events['event']=='view']['hour'],orientation='v',name='hour',)
# trace16 = go.Histogram(x=events[events['event']=='view']['day_of_week'],orientation='v',name='day_of_week',)
# trace17 = go.Histogram(x=events[events['event']=='view']['month'],orientation='v',name='month',)
# trace18 = go.Histogram(x=events[events['event']=='view']['day'],orientation='v',name='day',)
# trace19 = go.Histogram(x=events[events['event']=='view']['part_day'],orientation='v',name='part_day',)
# trace20 = go.Histogram(x=events[events['event']=='transaction']['Day Period'],orientation='v',name='part_day',)

# fig.append_trace(trace00, 1, 1)
# fig.append_trace(trace01, 2, 1)
# fig.append_trace(trace02, 3, 1)
# fig.append_trace(trace03, 4, 1)
# fig.append_trace(trace04, 5, 1)
# fig.append_trace(trace05, 6, 1)
# fig.append_trace(trace06, 7, 1)

# fig.append_trace(trace07, 1, 2)
# fig.append_trace(trace08, 2, 2)
# fig.append_trace(trace09, 3, 2)
# fig.append_trace(trace10, 4, 2)
# fig.append_trace(trace11, 5, 2)
# fig.append_trace(trace12, 6, 2)
# fig.append_trace(trace13, 7, 2)


# fig.append_trace(trace14, 1, 3)
# fig.append_trace(trace15, 2, 3)
# fig.append_trace(trace16, 3, 3)
# fig.append_trace(trace17, 4, 3)
# fig.append_trace(trace18, 5, 3)
# fig.append_trace(trace19, 6, 3)
# fig.append_trace(trace20, 7, 3)

# fig.update_layout(height=1800, width=1200,title_text='events',).show('png')
# fig.write_html("images/graf1.html")
# fig.write_image('images/img1.png')

In [12]:
events_pivot = events.pivot_table(
    index='visitorid',
    columns='event',
    aggfunc='size',
    fill_value=0
)

# fig = make_subplots(rows=3, cols=1,
#                     subplot_titles=['event = transaction', 'event = addtocart',' event = view',
#                                     ])

# trace00 = go.Histogram(x=events_pivot['transaction'],orientation='v',name='transaction',)
# trace01 = go.Histogram(x=events_pivot['addtocart'],orientation='v',name='addtocart',)
# trace02 = go.Histogram(x=events_pivot['view'],orientation='v',name='view',)


# fig.append_trace(trace00, 1, 1)
# fig.append_trace(trace01, 2, 1)
# fig.append_trace(trace02, 3, 1)


# fig.update_layout(height=900, width=900,title_text='events',)
# fig.write_html("images/graf2.html")
# fig.write_image('images/img2.png')

# fig.show()

На лицо море "ненормальных" пользователей у которых больше 6000 просмотров товаров, больше 500 addtocart и больше 500 транзакций. Такие пользователи только будут мешать обучению моделей.

Проверю на наличие "мертвых пользователей"

In [13]:
null_user = events_pivot[(events_pivot['transaction']==0) & (events_pivot['addtocart']==0) & (events_pivot['view']==0)].index
null_user

Index([], dtype='int64', name='visitorid')

In [14]:
odd_user = events_pivot[(events_pivot['transaction']>27) | (events_pivot['addtocart']>75) | (events_pivot['view']>255)].index
odd_user

Index([   6958,   17676,   38015,   48820,   53842,   54791,   57905,   73449,
         76757,   77390,
       ...
       1297062, 1313381, 1327144, 1332095, 1336835, 1348163, 1357576, 1376763,
       1385073, 1403769],
      dtype='int64', name='visitorid', length=150)

In [15]:
print(events.shape)
events = events[~events.visitorid.isin(odd_user)]
print(events.shape)

(2755641, 13)
(2635971, 13)

In [16]:
events_pivot = events.pivot_table(
    index='visitorid',
    columns='event',
    aggfunc='size',
    fill_value=0
)

# fig = make_subplots(rows=3, cols=1,
#                     subplot_titles=['event = transaction', 'event = addtocart',' event = view',
#                                     ])

# trace00 = go.Histogram(x=events_pivot['transaction'],orientation='v',name='transaction',)
# trace01 = go.Histogram(x=events_pivot['addtocart'],orientation='v',name='addtocart',)
# trace02 = go.Histogram(x=events_pivot['view'],orientation='v',name='view',)


# fig.append_trace(trace00, 1, 1)
# fig.append_trace(trace01, 2, 1)
# fig.append_trace(trace02, 3, 1)


# fig.update_layout(height=900, width=900,title_text='events',).show('png')
# fig.write_html("images/graf3.html")
# fig.write_image('images/img3.png')

In [17]:
events_pivot[events_pivot['view']==0]

event      addtocart  transaction  view
visitorid
1159               1            0     0
1399               2            0     0
1480               1            0     0
1742               1            0     0
2277               1            0     0
...              ...          ...   ...
1406820            1            0     0
1407059            1            0     0
1407319            1            0     0
1407398            1            1     0
1407515            1            0     0

[3400 rows x 3 columns]

Очень странное поведение пользователей: ни разу не увидел товар, но купил или добавил в корзиную Возможно стоит таких удалить!!

In [18]:
odd_user = events_pivot[events_pivot['view']==0].index
print(events.shape)
events = events[~events.visitorid.isin(odd_user)]
print(events.shape)

(2635971, 13)
(2631150, 13)

In [19]:
events.columns

Index(['timestamp', 'visitorid', 'event', 'itemid', 'transactionid',
       'day_of_week', 'year', 'month', 'day', 'hour', 'minute', 'part_day',
       'Day Period'],
      dtype='object')

In [20]:
events_grb = events.groupby('visitorid',as_index=False)['event'].count()
# px.histogram(events_grb['event']).show()
# fig.write_html("images/graf4.html")
# fig.write_image('images/img4.png')

In [21]:
events_grb

         visitorid  event
0                0      3
1                1      1
2                2      8
3                3      1
4                4      1
...            ...    ...
1404025    1407575      1
1404026    1407576      1
1404027    1407577      1
1404028    1407578      1
1404029    1407579      1

[1404030 rows x 2 columns]

Можно сократить датасет на пользователей, которые не проявляют активность, если за все время только одно или два действия, то это неактивные пользователи, можно их не учитывать

In [22]:
nonactive_user = events_grb[events_grb['event']<6 ].visitorid.to_list()

print(events.shape)
events = events[~events.visitorid.isin(nonactive_user)]
print(events.shape)

(2631150, 13)
(713150, 13)

In [23]:
events_grb = events.groupby('visitorid',as_index=False)['event'].count()
fig_events_grb = px.histogram(events_grb['event'])
fig_events_grb.write_html("images/graf5.html")
fig_events_grb.write_image('images/img5.png')
fig_events_grb.show()

In [ ]:
display(category_tree.describe(include='all'))

print(category_tree.isna().mean())
category_tree = category_tree.dropna()

        categoryid     parentid
count  1669.000000  1644.000000
mean    849.285201   847.571168
std     490.195116   505.058485
min       0.000000     8.000000
25%     427.000000   381.000000
50%     848.000000   866.000000
75%    1273.000000  1291.000000
max    1698.000000  1698.000000

categoryid    0.000000
parentid      0.014979
dtype: float64

In [25]:
display(item_properties.describe(include='all'))

                            timestamp        itemid  property     value
count                        20275902  2.027590e+07  20275902  20275902
unique                            NaN           NaN      1104   1966868
top                               NaN           NaN       888    769062
freq                              NaN           NaN   3000398   1537247
mean    2015-06-24 11:42:23.682878464  2.333904e+05       NaN       NaN
min               2015-05-10 00:00:00  0.000000e+00       NaN       NaN
25%               2015-05-24 00:00:00  1.165160e+05       NaN       NaN
50%               2015-06-07 00:00:00  2.334830e+05       NaN       NaN
75%               2015-07-26 00:00:00  3.503040e+05       NaN       NaN
max               2015-09-13 00:00:00  4.668660e+05       NaN       NaN
std                               NaN  1.348452e+05       NaN       NaN

In [26]:
(item_properties.isna().mean())

timestamp    0.0
itemid       0.0
property     0.0
value        0.0
dtype: float64

In [27]:
item_properties.sort_values(['timestamp','itemid'])[:25]

,timestamp,itemid,property,value
484093,2015-05-10,0,283,66094 372274 478989
2604501,2015-05-10,0,6,1152934 1238769
10592972,2015-05-10,0,159,519769
10958695,2015-05-10,0,678,372274
11431790,2015-05-10,0,790,n91200.000
19220984,2015-05-10,0,categoryid,209
2003267,2015-05-10,1,790,n5760.000
6307952,2015-05-10,1,available,1
7456814,2015-05-10,1,776,379040
8428979,2015-05-10,1,categoryid,1114
10154379,2015-05-10,1,888,172646
15263297,2015-05-10,1,112,679677
18246148,2015-05-10,1,159,519769
20148097,2015-05-10,1,6,1020281
6331205,2015-05-10,2,159,519769
6450071,2015-05-10,2,283,822092 325894 504272 147366 343631 648485 n600...
9157980,2015-05-10,2,categoryid,1305
12407569,2015-05-10,2,888,648485 n6000.000 n72.000 n72.000 468140
14427856,2015-05-10,2,112,679677
15900001,2015-05-10,2,764,1285872
16005973,2015-05-10,2,776,1005623
795922,2015-05-10,3,available,0
1330690,2015-05-10,3,678,327918
2465874,2015-05-10,3,283,138228 150169 1182824 327918 261419
7463203,2015-05-10,3,888,261419

In [28]:
temp = []
item_properties.property.apply(lambda x: x if x.isdigit() else temp.append(x))
set(temp)

{'available', 'categoryid'}

In [29]:
categoryid_properties = item_properties[item_properties['property'] == 'categoryid'].sort_values('itemid',ignore_index=True)
categoryid_properties = categoryid_properties.rename(columns={"value": "categoryid"}).drop('property',axis=1)
categoryid_properties.categoryid = categoryid_properties.categoryid.astype('int')
categoryid_properties[categoryid_properties['itemid']==25].sort_values('timestamp')

    timestamp  itemid  categoryid
31 2015-05-10      25        1509
27 2015-05-17      25        1509
40 2015-05-24      25        1509
34 2015-05-31      25        1509
26 2015-06-07      25        1509
39 2015-06-14      25        1509
24 2015-06-28      25        1509
28 2015-07-05      25        1509
30 2015-07-12      25        1509
37 2015-07-19      25        1509
33 2015-07-26      25        1509
36 2015-08-02      25        1509
32 2015-08-09      25        1509
38 2015-08-16      25          72
41 2015-08-23      25          72
25 2015-08-30      25          72
29 2015-09-06      25          72
35 2015-09-13      25          72

In [30]:
available = item_properties[item_properties['property'] == 'available'].sort_values('timestamp',ignore_index=True)
available = available.rename(columns={"value": "available"}).drop('property',axis=1)
available[available['itemid']==25].sort_values('timestamp')

         timestamp  itemid available
211094  2015-05-10      25         1
265518  2015-05-17      25         1
340241  2015-05-24      25         1
487801  2015-05-31      25         0
504836  2015-06-07      25         1
644560  2015-06-14      25         0
668013  2015-06-28      25         1
798758  2015-07-05      25         1
847150  2015-07-12      25         1
939426  2015-07-19      25         1
1004889 2015-07-26      25         1
1078534 2015-08-02      25         1
1135139 2015-08-09      25         0
1174763 2015-08-16      25         0
1233319 2015-08-23      25         0
1327715 2015-08-30      25         1
1418973 2015-09-06      25         1
1503384 2015-09-13      25         1

In [31]:
available.isna().mean()

timestamp    0.0
itemid       0.0
available    0.0
dtype: float64

In [32]:
start_date = available['timestamp'].min()
end_date = available['timestamp'].max()

In [33]:
# # # Применение функции к каждой группе пользователей
# available_full = available.groupby('itemid').apply(add_missing_sundays,start_date=start_date,end_date=end_date).ffill().bfill().reset_index(drop=True)

# available_full

In [34]:
# # # Производим сериализацию и записываем результат в файл формата pkl
# with open('data/available_full.pkl', 'wb') as output:
#     pickle.dump(available_full, output)

# # # Производим десериализацию и извлекаем из файла формата pkl
with open('data/available_full.pkl', 'rb') as pkl_file:
    available_full = pickle.load(pkl_file)

In [35]:
available_full.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7924007 entries, 0 to 7924006
Data columns (total 3 columns):
 #   Column     Dtype
---  ------     -----
 0   timestamp  datetime64[ns]
 1   itemid     float64
 2   available  object
dtypes: datetime64[ns](1), float64(1), object(1)
memory usage: 181.4+ MB

In [36]:
available_full[available_full['itemid']==8].sort_values('timestamp')[:25]

     timestamp  itemid available
152 2015-05-10     8.0         0
153 2015-05-17     8.0         0
154 2015-05-24     8.0         0
155 2015-05-31     8.0         0
156 2015-06-07     8.0         0
157 2015-06-14     8.0         0
158 2015-06-21     8.0         0
159 2015-06-28     8.0         0
160 2015-07-05     8.0         0
161 2015-07-12     8.0         0
162 2015-07-19     8.0         0
163 2015-07-26     8.0         0
164 2015-08-02     8.0         0
165 2015-08-09     8.0         0
166 2015-08-16     8.0         0
167 2015-08-23     8.0         0
168 2015-08-30     8.0         0
169 2015-09-06     8.0         0
170 2015-09-13     8.0         0

In [37]:
print('shape categoryid_properties : ', categoryid_properties.shape)
print('shape available_full : ', available_full.shape)

shape categoryid_properties :  (788214, 3)
shape available_full :  (7924007, 3)

In [38]:
categoryid_properties = categoryid_properties.merge(category_tree,on='categoryid',how='left')
# display(categoryid_properties)
print('shape categoryid_properties : ', categoryid_properties.shape)
print(categoryid_properties['parentid'].isna().sum())
categoryid_properties = categoryid_properties.dropna()
print(categoryid_properties['parentid'].isna().sum())
print('shape categoryid_properties : ', categoryid_properties.shape)

shape categoryid_properties :  (788214, 4)
218
0
shape categoryid_properties :  (787996, 4)

In [39]:
# cat_prop_full = categoryid_properties.groupby('itemid').apply(add_missing_sundays,start_date=start_date,end_date=end_date).ffill().bfill().reset_index(drop=True)

In [40]:
# Производим сериализацию и записываем результат в файл формата pkl
# with open('data/cat_prop_full.pkl', 'wb') as output:
#     pickle.dump(cat_prop_full, output)

# # # Производим десериализацию и извлекаем из файла формата pkl
with open('data/cat_prop_full.pkl', 'rb') as pkl_file:
    cat_prop_full = pickle.load(pkl_file)

In [41]:
cat_prop_full[cat_prop_full['itemid']==8].sort_values('timestamp')[:25]

     timestamp  itemid  categoryid  parentid
152 2015-05-10     8.0       512.0     362.0
153 2015-05-17     8.0       512.0     362.0
154 2015-05-24     8.0       512.0     362.0
155 2015-05-31     8.0       512.0     362.0
156 2015-06-07     8.0       512.0     362.0
157 2015-06-14     8.0       512.0     362.0
158 2015-06-21     8.0       512.0     362.0
159 2015-06-28     8.0       173.0     788.0
160 2015-07-05     8.0       173.0     788.0
161 2015-07-12     8.0       173.0     788.0
162 2015-07-19     8.0       173.0     788.0
163 2015-07-26     8.0       173.0     788.0
164 2015-08-02     8.0       173.0     788.0
165 2015-08-09     8.0       173.0     788.0
166 2015-08-16     8.0       173.0     788.0
167 2015-08-23     8.0       173.0     788.0
168 2015-08-30     8.0       173.0     788.0
169 2015-09-06     8.0       173.0     788.0
170 2015-09-13     8.0       173.0     788.0

In [42]:
print(cat_prop_full['parentid'].isna().sum())
print('shape categoryid_properties : ', cat_prop_full.shape)

0
shape categoryid_properties :  (7921043, 4)

In [43]:
cat_prop_full.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7921043 entries, 0 to 7921042
Data columns (total 4 columns):
 #   Column      Dtype
---  ------      -----
 0   timestamp   datetime64[ns]
 1   itemid      float64
 2   categoryid  float64
 3   parentid    float64
dtypes: datetime64[ns](1), float64(3)
memory usage: 241.7 MB

In [44]:
itm_prop = item_properties[(item_properties['property'] != 'available')&(item_properties['property'] != 'categoryid')]
display(itm_prop.info())
display(itm_prop.head())

<class 'pandas.core.frame.DataFrame'>
Index: 17984049 entries, 1 to 20275901
Data columns (total 4 columns):
 #   Column     Dtype
---  ------     -----
 0   timestamp  datetime64[ns]
 1   itemid     int64
 2   property   object
 3   value      object
dtypes: datetime64[ns](1), int64(1), object(2)
memory usage: 686.0+ MB

None

   timestamp  itemid property                            value
1 2015-09-06  206783      888          1116713 960601 n277.200
2 2015-08-09  395014      400  n552.000 639502 n720.000 424566
3 2015-05-10   59481      790                       n15360.000
4 2015-05-17  156781      917                           828513
6 2015-06-14   89534      213                          1121373

In [45]:
display(itm_prop.info(),)

<class 'pandas.core.frame.DataFrame'>
Index: 17984049 entries, 1 to 20275901
Data columns (total 4 columns):
 #   Column     Dtype
---  ------     -----
 0   timestamp  datetime64[ns]
 1   itemid     int64
 2   property   object
 3   value      object
dtypes: datetime64[ns](1), int64(1), object(2)
memory usage: 686.0+ MB

None

In [46]:
itm_prop = itm_prop.merge(cat_prop_full,on=['timestamp','itemid'],how='left')
itm_prop = itm_prop.merge(available_full, on=['timestamp','itemid'],how='left')
itm_prop = itm_prop.sort_values('timestamp')

In [47]:
itm_prop.isna().mean()*100

timestamp     0.000000
itemid        0.000000
property      0.000000
value         0.000000
categoryid    0.017994
parentid      0.017994
available     0.000000
dtype: float64

In [48]:
itm_prop = itm_prop.fillna(1111111111)
itm_prop.isna().mean()*100

timestamp     0.0
itemid        0.0
property      0.0
value         0.0
categoryid    0.0
parentid      0.0
available     0.0
dtype: float64

In [49]:
# # # Производим сериализацию и записываем результат в файл формата pkl
# with open('data/itm_prop.pkl', 'wb') as output:
#     pickle.dump(itm_prop, output)


# # # # Производим десериализацию и извлекаем из файла формата pkl
# with open('data/itm_prop.pkl', 'rb') as pkl_file:
#     itm_prop = pickle.load(pkl_file)

Типы событий ['view', 'addtocart', 'transaction'], их необходимо превести в числовой вид.  
Здесь можно играться с коэффициентами , для улучшения качества. Но так как нас интересуют продажи, то ввела такие коэффициеты.

In [50]:
event_type = {
            'view': 1,
            'addtocart':2,
            'transaction': 5,
            }

events['event'] = events['event'].replace(event_type)

In [51]:
train, test = train_test_split(events, test_size=0.3, shuffle=False)

print(train.shape[0] / events.shape[0])
print(test.shape[0] / events.shape[0])

0.7
0.3

In [52]:
# Построен валидационный датасет (разбивка по времени)
# На мой взгляд так более правильно (в соответствии с заданием)

split_date = '2015-08-03' # Почему именно такая дата: чтобы разбика примерно была  в соотношении как в эталонном примере 70:30
train_time = events[events['timestamp'].dt.strftime('%Y-%m-%d') < split_date]
test_time = events[events['timestamp'].dt.strftime('%Y-%m-%d') >= split_date]

print(train_time.shape[0] / events.shape[0])
print(test_time.shape[0] / events.shape[0])

0.7324742340321111
0.26752576596788896

In [53]:
# # Производим сериализацию и записываем результат в файл формата pkl
with open('data/train_time.pkl', 'wb') as output:
    pickle.dump(train_time, output)

with open('data/test_time.pkl', 'wb') as output:
    pickle.dump(test_time, output)

# Создание факторов для модели

Факторы в рекомендательных системах — это скрытые переменные, которые описывают взаимодействия пользователей и объектов (например, товаров или фильмов). Эти факторы помогают предсказать предпочтения пользователей. Проще говоря, факторы — это параметры, которые используются для создания персонализированных рекомендаций.

Примеры факторов:  
* Пользовательские предпочтения: Интересы, возраст, пол, прошлые действия, история покупок и просмотров.
* Свойства объектов: Жанр фильма, категория товара, цена, рейтинг.
* Контекст: Время суток, место нахождения, устройство, с которого выполняется доступ.

Каждый пользователь и каждый объект могут быть представлены как векторы в пространстве факторов. Модель пытается минимизировать ошибку предсказания, находя оптимальные векторы для пользователей и объектов, чтобы сделать точные рекомендации.

Временные факторы созданы в ноутбуке **first_second_week.ipynb**

### Генерация факторов айтем-юзер

Генерация факторов айтем-юзер

Генерация факторов, связанных как с пользователями (юзерами), так и с айтемами (объектами), позволяет создать более точные и персонализированные рекомендации. Давай рассмотрим, какие факторы можно использовать:

Факторы пользователей:
* История покупок/просмотров: Какие товары пользователь уже покупал или просматривал.
* Возраст, пол, местоположение: Демографическая информация.
* Интересы и предпочтения: Например, жанры фильмов или категории товаров.
Взаимодействия с системой: Лайки, отзывы, время, проведенное на сайте.

Факторы айтемов:
* Категория: Классификация товара.
* Бренд: Производитель или марка.
* Цена: Стоимость.
* Рейтинг: Средние оценки пользователей.
* Описание: Текстовое описание или ключевые слова.
* Изображения: Визуальные характеристики.

In [54]:
# Создание разреженной матрицы item-user
train_item_user_matrix = csr_matrix((train['event'],(train['itemid'], train['visitorid'])))
test_item_user_matrix = csr_matrix((test['event'],(test['itemid'], test['visitorid'])))

item_user_matrix = csr_matrix((events['event'],(events['itemid'], events['visitorid'])))

### Генерация факторов, связанных с айтемами

Генерация факторов, связанных с айтемами (items), — ключевой процесс в рекомендательных системах. Эти факторы помогают системе лучше понять и предсказать предпочтения пользователей. Вот примеры таких факторов:

* Категория: Определенная категория, к которой относится товар (например, книги, электроника, одежда).  
* Бренд: Название бренда или производителя товара.  
* Цена: Стоимость товара.  
* Рейтинг: Оценки, оставленные пользователями.  
* Дата выпуска: Когда товар был впервые выпущен или добавлен в систему.  
* Текстовое описание: Ключевые слова из описания или названия товара.  
* Изображения: Особенности изображений товаров, такие как цвет, форма и др.  
* Популярность: Сколько раз товар был просмотрен или куплен пользователями.  

Использование этих факторов позволяет системе предоставлять более точные и персонализированные рекомендации.

Воспользуюсь подсказкой ментора из Пачки

In [55]:
# Инициализация ALS модели
als_model = AlternatingLeastSquares(factors=100, regularization=0.1, iterations=100)

# Обучение модели ALS
als_model.fit(item_user_matrix)

# Получение факторов для айтемов
item_factors = als_model.item_factors

# Создание DataFrame с факторами айтемов
item_factors_df = pd.DataFrame(item_factors, index=range(1, item_factors.shape[0] + 1), columns=[f'item_factor_{i}' for i in range(item_factors.shape[1])])

# Добавление факторов айтемов к исходному датасету с айтемами
# items_with_factors = pd.merge(events, item_factors_df, left_on='itemid', right_index=True, how='left')
events = pd.merge(events, item_factors_df, left_on='itemid', right_index=True, how='left')

events.head(3)

c:\Users\olgas\anaconda3\envs\virt_cute_ranking\lib\site-packages\implicit\cpu\als.py:95: RuntimeWarning:

OpenBLAS is configured to use 3 threads. It is highly recommended to disable its internal threadpool by setting the environment variable 'OPENBLAS_NUM_THREADS=1' or by calling 'threadpoolctl.threadpool_limits(1, "blas")'. Having OpenBLAS use a threadpool can lead to severe performance issues here.

c:\Users\olgas\anaconda3\envs\virt_cute_ranking\lib\site-packages\implicit\cpu\als.py:95: RuntimeWarning:

Intel MKL BLAS is configured to use 3 threads. It is highly recommended to disable its internal threadpool by setting the environment variable 'MKL_NUM_THREADS=1' or by callng 'threadpoolctl.threadpool_limits(1, "blas")'. Having MKL use a threadpool can lead to severe performance issues

  0%|          | 0/100 [00:00<?, ?it/s]

,timestamp,visitorid,event,itemid,transactionid,day_of_week,year,month,day,hour,...,item_factor_90,item_factor_91,item_factor_92,item_factor_93,item_factor_94,item_factor_95,item_factor_96,item_factor_97,item_factor_98,item_factor_99
1,2015-06-02 05:50:14.164,992329,1,248676,NaN,1,2015,6,2,5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,2015-06-02 05:47:50.841,1398644,1,135256,NaN,1,2015,6,2,5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24,2015-06-02 05:33:23.944,125625,1,17655,NaN,1,2015,6,2,5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [56]:
# # Производим сериализацию и записываем результат в файл формата pkl
with open('data/events_cl.pkl', 'wb') as output:
    pickle.dump(events, output)