In [26]:
import numpy as np
import scipy
import pickle
import pandas as pd

from implicit.als import AlternatingLeastSquares
from implicit.cpu.bpr import BayesianPersonalizedRanking
from implicit.cpu.lmf import LogisticMatrixFactorization
from implicit.nearest_neighbours import CosineRecommender
from implicit.cpu.matrix_factorization_base import MatrixFactorizationBase

from implicit.evaluation import ranking_metrics_at_k

from sklearn.model_selection import train_test_split
from scipy.sparse import csr_matrix

In [2]:
# import psutil

# # Получение информации о памяти
# memory_info = psutil.virtual_memory()
# print(memory_info)

In [3]:
import gc
gc.collect()

0

In [4]:
import os
import threadpoolctl

os.environ['MKL_NUM_THREADS'] = '5'
os.environ['OPENBLAS_NUM_THREADS'] = '5'
os.environ['OMP_NUM_THREADS'] = '5'

threadpoolctl.threadpool_limits(5, "blas")

In [5]:
random_state = 42

In [6]:
# # # Производим десериализацию и извлекаем из файла формата pkl
with open('data\events_cl.pkl', 'rb') as pkl_file:
    events = pickle.load(pkl_file)

events = events[['timestamp','visitorid','event','itemid']]
events.head()

                 timestamp  visitorid  event  itemid
1  2015-06-02 05:50:14.164     992329      1  248676
20 2015-06-02 05:47:50.841    1398644      1  135256
24 2015-06-02 05:33:23.944     125625      1   17655
27 2015-06-02 05:15:47.345    1076270      1  262799
29 2015-06-02 05:02:57.547    1153198      1  388242

In [7]:
events = events.sample(frac=0.10, random_state=random_state)

In [8]:
# Построен валидационный датасет (разбивка по времени)
# На мой взгляд так более правильно (в соответствии с заданием)

split_date = '2015-08-03'
train = events[events['timestamp'].dt.strftime('%Y-%m-%d') < split_date]
test = events[events['timestamp'].dt.strftime('%Y-%m-%d') >= split_date]

print(train.shape[0] / events.shape[0])
print(test.shape[0] / events.shape[0])

0.7333239851363669
0.2666760148636332

In [9]:
events = events[['visitorid','event','itemid']]
train = train[['visitorid','event','itemid']]
test = test[['visitorid','event','itemid']]

Чтобы обучить ALS-модель на предоставленных данных, нужно создать user-item таблицу для тренировочной и тестовой выборки. В этой таблице по строкам должны быть отложены идентификаторы всех уникальных пользователей, которые у нас есть, а по столбцам — все уникальные фильмы. То есть мы должны получить две матрицы размерности 943 x 1682. На пересечении строк и столбцов этих матриц должны быть числа, характеризующие наличие положительных и отрицательных оценок пользователей.

In [10]:
for df in [train, test, events]:
    if (df[['visitorid', 'itemid', 'event']] < 0).any().any():
        print("Есть отрицательные значения в данных.")
        df[df[['visitorid', 'itemid', 'event']] < 0] = 0

In [11]:
assert (train[['visitorid', 'itemid', 'event']] >= 0).all().all(), "Есть отрицательные значения!"

In [12]:
train_pivot = pd.pivot_table(
                        train,
                        index="visitorid",
                        columns="itemid",
                        values="event",
                        )

In [13]:
test_pivot = pd.pivot_table(
                    test,
                    index="visitorid",
                    columns="itemid",
                    values="event"
                    )

In [14]:
del test
del train

In [15]:
shell = pd.pivot_table(
                events,
                index="visitorid",
                columns="itemid",
                values="event",
                aggfunc=lambda x: 0
                )


print(train_pivot.shape)
print(test_pivot.shape)

(27293, 25223)
(10917, 11851)

In [16]:
train_pivot = shell + train_pivot
test_pivot = shell + test_pivot


train_pivot = (train_pivot + 1).fillna(0)
test_pivot = (test_pivot + 1).fillna(0)


print(train_pivot.shape)
print(test_pivot.shape)


train_pivot.head()

(36824, 31613)
(36824, 31613)

itemid,6,15,16,19,25,32,42,124,147,168,...,466710,466757,466772,466789,466796,466830,466844,466847,466861,466864
visitorid,,,,,,,,,,,,,,,,,,,,,
37,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
75,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
155,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
172,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
264,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [17]:
train_pivot_sparse = scipy.sparse.csr_matrix(train_pivot.values)
test_pivot_sparse = scipy.sparse.csr_matrix(test_pivot.values)

In [18]:
model = AlternatingLeastSquares(random_state=random_state)
model.fit(train_pivot_sparse)

c:\Users\olgas\anaconda3\envs\virt_cute_ranking\lib\site-packages\implicit\cpu\als.py:95: RuntimeWarning: OpenBLAS is configured to use 5 threads. It is highly recommended to disable its internal threadpool by setting the environment variable 'OPENBLAS_NUM_THREADS=1' or by calling 'threadpoolctl.threadpool_limits(1, "blas")'. Having OpenBLAS use a threadpool can lead to severe performance issues here.
  check_blas_config()
c:\Users\olgas\anaconda3\envs\virt_cute_ranking\lib\site-packages\implicit\cpu\als.py:95: RuntimeWarning: Intel MKL BLAS is configured to use 5 threads. It is highly recommended to disable its internal threadpool by setting the environment variable 'MKL_NUM_THREADS=1' or by callng 'threadpoolctl.threadpool_limits(1, "blas")'. Having MKL use a threadpool can lead to severe performance issues
  check_blas_config()

  0%|          | 0/15 [00:00<?, ?it/s]

In [19]:
unique_items = np.array(train_pivot.columns)
user_id = 14
recomendations_ids, scores = model.recommend(user_id, train_pivot_sparse[user_id])
recomendations = unique_items[recomendations_ids]

print('Recomendations for user {}: {}'.format(user_id, recomendations))

Recomendations for user 14: [373128 422356 456005 277490 465951  80502 404033 328696  97039 166306]

In [20]:
# map_at10 = mean_average_precision_at_k(model, train_pivot_sparse, test_pivot_sparse, K=3)
# print('Mean Average Precision at 10: {:.3f}'.format(map_at10))

  0%|          | 0/10917 [00:00<?, ?it/s]

Mean Average Precision at 10: 0.001

In [31]:
models = [
        AlternatingLeastSquares(random_state=random_state),
        BayesianPersonalizedRanking(random_state=random_state),
        LogisticMatrixFactorization(random_state=random_state),
        CosineRecommender(),
        ]
result_map_at10 = []
result_ndcg_at_k = []
result_auc = []


for model in models:
    print(model)
    model.fit(train_pivot_sparse)

    temp = ranking_metrics_at_k(model, train_pivot_sparse, test_pivot_sparse, K=10)
    result_map_at10.append(temp['map'])
    result_ndcg_at_k.append(temp['ndcg'])
    result_auc.append(temp['auc'])


models_name = []
for i in range(len(models)):
    models_name.append(str(models[i]))


df_rez = pd.DataFrame(data=[models_name, result_map_at10, result_ndcg_at_k, result_auc]).T
df_rez.columns = ['model', 'map_at10', 'result_ndcg_at_k', 'result_auc']
df_rez

<implicit.cpu.als.AlternatingLeastSquares object at 0x00000199187E5850>

  0%|          | 0/15 [00:00<?, ?it/s]

  0%|          | 0/10917 [00:00<?, ?it/s]

<implicit.cpu.bpr.BayesianPersonalizedRanking object at 0x00000199187E5BB0>

  0%|          | 0/100 [00:00<?, ?it/s]

  0%|          | 0/10917 [00:00<?, ?it/s]

<implicit.cpu.lmf.LogisticMatrixFactorization object at 0x00000199187E5BE0>

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/10917 [00:00<?, ?it/s]

<implicit.nearest_neighbours.CosineRecommender object at 0x00000199187E5EE0>

c:\Users\olgas\anaconda3\envs\virt_cute_ranking\lib\site-packages\implicit\utils.py:164: ParameterWarning: Method expects CSR input, and was passed coo_matrix instead. Converting to CSR took 0.0 seconds
  warnings.warn(

  0%|          | 0/31613 [00:00<?, ?it/s]

  0%|          | 0/10917 [00:00<?, ?it/s]

,model,map_at10,result_ndcg_at_k,result_auc
0,<implicit.cpu.als.AlternatingLeastSquares obje...,0.00066,0.000864,0.500453
1,<implicit.cpu.bpr.BayesianPersonalizedRanking ...,0.000143,0.00023,0.500056
2,<implicit.cpu.lmf.LogisticMatrixFactorization ...,0.002654,0.003795,0.502673
3,<implicit.nearest_neighbours.CosineRecommender...,0.008052,0.009545,0.506422

In [41]:
def opt_Ext(trial):
    # задаем пространство поиска гиперпараметров

    K = trial.suggest_categorical('K',[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,17,20,25,30,])


    # создаем модель
    model = CosineRecommender(K=K,)

    model.fit(train_pivot_sparse)

    score = ranking_metrics_at_k(model, train_pivot_sparse, test_pivot_sparse, K=10)['ndcg']
    return score

In [42]:
import optuna
# cоздаем объект исследования
# можем напрямую указать, что нам необходимо минимизировать метрику direction="minimize"
stud = optuna.create_study(direction="maximize")


# ищем лучшую комбинацию гиперпараметров
stud.optimize(opt_Ext, n_trials=30)

[I 2024-10-23 16:18:47,557] A new study created in memory with name: no-name-20a4b4a3-ee3b-4b90-a65c-4f7fa66980d1

  0%|          | 0/31613 [00:00<?, ?it/s]

  0%|          | 0/10917 [00:00<?, ?it/s]

[I 2024-10-23 16:18:49,363] Trial 0 finished with value: 0.009563108297293321 and parameters: {'K': 25}. Best is trial 0 with value: 0.009563108297293321.

  0%|          | 0/31613 [00:00<?, ?it/s]

  0%|          | 0/10917 [00:00<?, ?it/s]

[I 2024-10-23 16:18:51,104] Trial 1 finished with value: 0.013053394815070899 and parameters: {'K': 2}. Best is trial 1 with value: 0.013053394815070899.

  0%|          | 0/31613 [00:00<?, ?it/s]

  0%|          | 0/10917 [00:00<?, ?it/s]

[I 2024-10-23 16:18:52,853] Trial 2 finished with value: 0.010830945876248495 and parameters: {'K': 6}. Best is trial 1 with value: 0.013053394815070899.
c:\Users\olgas\anaconda3\envs\virt_cute_ranking\lib\site-packages\implicit\utils.py:164: ParameterWarning: Method expects CSR input, and was passed coo_matrix instead. Converting to CSR took 0.0010099411010742188 seconds
  warnings.warn(

  0%|          | 0/31613 [00:00<?, ?it/s]

  0%|          | 0/10917 [00:00<?, ?it/s]

[I 2024-10-23 16:18:54,617] Trial 3 finished with value: 0.010596138089093666 and parameters: {'K': 7}. Best is trial 1 with value: 0.013053394815070899.

  0%|          | 0/31613 [00:00<?, ?it/s]

  0%|          | 0/10917 [00:00<?, ?it/s]

[I 2024-10-23 16:18:56,382] Trial 4 finished with value: 0.013053394815070899 and parameters: {'K': 2}. Best is trial 1 with value: 0.013053394815070899.
c:\Users\olgas\anaconda3\envs\virt_cute_ranking\lib\site-packages\implicit\utils.py:164: ParameterWarning: Method expects CSR input, and was passed coo_matrix instead. Converting to CSR took 0.0009307861328125 seconds
  warnings.warn(

  0%|          | 0/31613 [00:00<?, ?it/s]

  0%|          | 0/10917 [00:00<?, ?it/s]

[I 2024-10-23 16:18:58,103] Trial 5 finished with value: 0.009555727033002002 and parameters: {'K': 14}. Best is trial 1 with value: 0.013053394815070899.

  0%|          | 0/31613 [00:00<?, ?it/s]

  0%|          | 0/10917 [00:00<?, ?it/s]

[I 2024-10-23 16:18:59,871] Trial 6 finished with value: 0.009555727033002002 and parameters: {'K': 15}. Best is trial 1 with value: 0.013053394815070899.
c:\Users\olgas\anaconda3\envs\virt_cute_ranking\lib\site-packages\implicit\utils.py:164: ParameterWarning: Method expects CSR input, and was passed coo_matrix instead. Converting to CSR took 0.0003490447998046875 seconds
  warnings.warn(

  0%|          | 0/31613 [00:00<?, ?it/s]

  0%|          | 0/10917 [00:00<?, ?it/s]

[I 2024-10-23 16:19:01,689] Trial 7 finished with value: 0.009563108297293321 and parameters: {'K': 30}. Best is trial 1 with value: 0.013053394815070899.
c:\Users\olgas\anaconda3\envs\virt_cute_ranking\lib\site-packages\implicit\utils.py:164: ParameterWarning: Method expects CSR input, and was passed coo_matrix instead. Converting to CSR took 0.0007617473602294922 seconds
  warnings.warn(

  0%|          | 0/31613 [00:00<?, ?it/s]

  0%|          | 0/10917 [00:00<?, ?it/s]

[I 2024-10-23 16:19:03,452] Trial 8 finished with value: 0.013053394815070899 and parameters: {'K': 2}. Best is trial 1 with value: 0.013053394815070899.
c:\Users\olgas\anaconda3\envs\virt_cute_ranking\lib\site-packages\implicit\utils.py:164: ParameterWarning: Method expects CSR input, and was passed coo_matrix instead. Converting to CSR took 0.0005848407745361328 seconds
  warnings.warn(

  0%|          | 0/31613 [00:00<?, ?it/s]

  0%|          | 0/10917 [00:00<?, ?it/s]

[I 2024-10-23 16:19:05,203] Trial 9 finished with value: 0.013053394815070899 and parameters: {'K': 2}. Best is trial 1 with value: 0.013053394815070899.

  0%|          | 0/31613 [00:00<?, ?it/s]

  0%|          | 0/10917 [00:00<?, ?it/s]

[I 2024-10-23 16:19:06,930] Trial 10 finished with value: 0.009545390389111836 and parameters: {'K': 17}. Best is trial 1 with value: 0.013053394815070899.

  0%|          | 0/31613 [00:00<?, ?it/s]

  0%|          | 0/10917 [00:00<?, ?it/s]

[I 2024-10-23 16:19:08,758] Trial 11 finished with value: 0.009545390389111836 and parameters: {'K': 20}. Best is trial 1 with value: 0.013053394815070899.

  0%|          | 0/31613 [00:00<?, ?it/s]

  0%|          | 0/10917 [00:00<?, ?it/s]

[I 2024-10-23 16:19:10,619] Trial 12 finished with value: 0.009609890164118158 and parameters: {'K': 12}. Best is trial 1 with value: 0.013053394815070899.

  0%|          | 0/31613 [00:00<?, ?it/s]

  0%|          | 0/10917 [00:00<?, ?it/s]

[I 2024-10-23 16:19:12,463] Trial 13 finished with value: 0.010281061443522121 and parameters: {'K': 9}. Best is trial 1 with value: 0.013053394815070899.

  0%|          | 0/31613 [00:00<?, ?it/s]

  0%|          | 0/10917 [00:00<?, ?it/s]

[I 2024-10-23 16:19:14,308] Trial 14 finished with value: 0.011194917708272956 and parameters: {'K': 5}. Best is trial 1 with value: 0.013053394815070899.

  0%|          | 0/31613 [00:00<?, ?it/s]

  0%|          | 0/10917 [00:00<?, ?it/s]

[I 2024-10-23 16:19:16,137] Trial 15 finished with value: 0.013053394815070899 and parameters: {'K': 2}. Best is trial 1 with value: 0.013053394815070899.

  0%|          | 0/31613 [00:00<?, ?it/s]

  0%|          | 0/10917 [00:00<?, ?it/s]

[I 2024-10-23 16:19:17,997] Trial 16 finished with value: 0.01014621435117924 and parameters: {'K': 10}. Best is trial 1 with value: 0.013053394815070899.

  0%|          | 0/31613 [00:00<?, ?it/s]

  0%|          | 0/10917 [00:00<?, ?it/s]

[I 2024-10-23 16:19:19,919] Trial 17 finished with value: 0.016190243370952102 and parameters: {'K': 1}. Best is trial 17 with value: 0.016190243370952102.

  0%|          | 0/31613 [00:00<?, ?it/s]

  0%|          | 0/10917 [00:00<?, ?it/s]

[I 2024-10-23 16:19:21,826] Trial 18 finished with value: 0.016190243370952102 and parameters: {'K': 1}. Best is trial 17 with value: 0.016190243370952102.

  0%|          | 0/31613 [00:00<?, ?it/s]

  0%|          | 0/10917 [00:00<?, ?it/s]

[I 2024-10-23 16:19:23,655] Trial 19 finished with value: 0.016190243370952102 and parameters: {'K': 1}. Best is trial 17 with value: 0.016190243370952102.

  0%|          | 0/31613 [00:00<?, ?it/s]

  0%|          | 0/10917 [00:00<?, ?it/s]

[I 2024-10-23 16:19:25,562] Trial 20 finished with value: 0.016190243370952102 and parameters: {'K': 1}. Best is trial 17 with value: 0.016190243370952102.

  0%|          | 0/31613 [00:00<?, ?it/s]

  0%|          | 0/10917 [00:00<?, ?it/s]

[I 2024-10-23 16:19:27,391] Trial 21 finished with value: 0.010438289304903894 and parameters: {'K': 8}. Best is trial 17 with value: 0.016190243370952102.

  0%|          | 0/31613 [00:00<?, ?it/s]

  0%|          | 0/10917 [00:00<?, ?it/s]

[I 2024-10-23 16:19:29,251] Trial 22 finished with value: 0.016190243370952102 and parameters: {'K': 1}. Best is trial 17 with value: 0.016190243370952102.

  0%|          | 0/31613 [00:00<?, ?it/s]

  0%|          | 0/10917 [00:00<?, ?it/s]

[I 2024-10-23 16:19:31,125] Trial 23 finished with value: 0.016190243370952102 and parameters: {'K': 1}. Best is trial 17 with value: 0.016190243370952102.

  0%|          | 0/31613 [00:00<?, ?it/s]

  0%|          | 0/10917 [00:00<?, ?it/s]

[I 2024-10-23 16:19:32,954] Trial 24 finished with value: 0.016190243370952102 and parameters: {'K': 1}. Best is trial 17 with value: 0.016190243370952102.

  0%|          | 0/31613 [00:00<?, ?it/s]

  0%|          | 0/10917 [00:00<?, ?it/s]

[I 2024-10-23 16:19:34,845] Trial 25 finished with value: 0.00957368788045668 and parameters: {'K': 13}. Best is trial 17 with value: 0.016190243370952102.

  0%|          | 0/31613 [00:00<?, ?it/s]

  0%|          | 0/10917 [00:00<?, ?it/s]

[I 2024-10-23 16:19:36,690] Trial 26 finished with value: 0.011498679802506318 and parameters: {'K': 4}. Best is trial 17 with value: 0.016190243370952102.

  0%|          | 0/31613 [00:00<?, ?it/s]

  0%|          | 0/10917 [00:00<?, ?it/s]

[I 2024-10-23 16:19:38,503] Trial 27 finished with value: 0.00966312862757183 and parameters: {'K': 11}. Best is trial 17 with value: 0.016190243370952102.

  0%|          | 0/31613 [00:00<?, ?it/s]

  0%|          | 0/10917 [00:00<?, ?it/s]

[I 2024-10-23 16:19:40,364] Trial 28 finished with value: 0.01205462667382057 and parameters: {'K': 3}. Best is trial 17 with value: 0.016190243370952102.

  0%|          | 0/31613 [00:00<?, ?it/s]

  0%|          | 0/10917 [00:00<?, ?it/s]

[I 2024-10-23 16:19:42,209] Trial 29 finished with value: 0.009563108297293321 and parameters: {'K': 25}. Best is trial 17 with value: 0.016190243370952102.

In [43]:
print(stud.best_params)

{'K': 1}

In [45]:
best_model_implicit = CosineRecommender(K=stud.best_params['K'])

best_model_implicit.fit(train_pivot_sparse)


# # Производим сериализацию и записываем результат в файл формата pkl
with open(r'models\best_model_implicit.pkl', 'wb') as output:
    pickle.dump(best_model_implicit, output)

c:\Users\olgas\anaconda3\envs\virt_cute_ranking\lib\site-packages\implicit\utils.py:164: ParameterWarning: Method expects CSR input, and was passed coo_matrix instead. Converting to CSR took 0.0 seconds
  warnings.warn(

  0%|          | 0/31613 [00:00<?, ?it/s]

In [49]:
temp = ranking_metrics_at_k(best_model_implicit, train_pivot_sparse, test_pivot_sparse, K=10)
temp

  0%|          | 0/10917 [00:00<?, ?it/s]

{'precision': 0.01346142442032853,
 'map': 0.015242064582542743,
 'ndcg': 0.016190243370952102,
 'auc': 0.5084381683553778}