In [1]:
from surprise import  KNNBasic,KNNWithMeans,KNNWithZScore,KNNBaseline,SVD,SVDpp,NMF,BaselineOnly,CoClustering
from surprise import Dataset
from surprise.accuracy import rmse, mae, fcp
from surprise import Reader

import pandas as pd
import pickle


import optuna

In [2]:
random_state=42

Surprise используется в различных областях для построения и оценки рекомендательных систем. Вот некоторые из них:

* Электронная коммерция: Рекомендации товаров и услуг на основе предыдущих покупок и просмотров пользователей.
* Платформы потокового вещания: Рекомендации фильмов, сериалов и музыки на основе предпочтений пользователей и их взаимодействий.
* Социальные сети: Персонализированные рекомендации друзей, групп и контента.
* Образование: Рекомендации курсов и учебных материалов на основе прошлых успехов и интересов студентов.
* Новости и контент: Рекомендации новостных статей и других информационных материалов на основе предпочтений пользователей.

Surprise помогает создавать точные и персонализированные рекомендации, улучшая опыт пользователей в различных сферах.

In [3]:
# # # Производим десериализацию и извлекаем из файла формата pkl
with open('data/train_time.pkl', 'rb') as pkl_file:
    train = pickle.load(pkl_file)

with open('data/test_time.pkl', 'rb') as pkl_file:
    test = pickle.load(pkl_file)

In [4]:
train = train.sample(frac=0.13, random_state=random_state)

In [5]:
train = train.groupby(['visitorid','itemid'],as_index=False)['event'].sum()
test = test.groupby(['visitorid','itemid'],as_index=False)['event'].sum()

In [6]:
# train.event = train.event.astype('int16')
# test.event = test.event.astype('int16')

In [7]:
train = train[["itemid", "visitorid", "event"]].rename(columns={"itemid": "iid","visitorid": "uid",'event':'r_ui'})
test = test[["itemid", "visitorid", "event"]].rename(columns={"itemid": "iid","visitorid": "uid",'event':'r_ui'})

In [8]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108093 entries, 0 to 108092
Data columns (total 3 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   iid     108093 non-null  int64
 1   uid     108093 non-null  int64
 2   r_ui    108093 non-null  int64
dtypes: int64(3)
memory usage: 2.5 MB

In [9]:
train

          iid      uid  r_ui
0       57171       74     0
1      257575       75     0
2      400946       97     0
3       10034      172     0
4      374400      172     0
...       ...      ...   ...
58099  107832  1407512     0
58100  118079  1407512     0
58101  241408  1407512     0
58102  441579  1407512     0
58103   13961  1407573     0

[58104 rows x 3 columns]

In [10]:
test.r_ui.max()

5

Классы в surprise принимают данные через свой отдельный класс Dataset, в который мы отправляем данные и класс Reader с указанным диапазоном допустимых оценок:

In [11]:
# Создание Reader и Dataset
reader = Reader(rating_scale=(1, 300))
train_data = Dataset.load_from_df(train[['uid', 'iid', 'r_ui']], reader)
test_data = Dataset.load_from_df(test[['uid', 'iid', 'r_ui']], reader)

# Создание полного тренировочного набора
trainset = train_data.build_full_trainset()

# Преобразование тестового набора в формат списков кортежей
raw_testset = [(uid, iid, r_ui) for (uid, iid, r_ui) in zip(test['uid'], test['iid'], test['r_ui'])]

Виды моделей в библиотеке surprise
* KNNBasic: Простой алгоритм ближайших соседей (K-Nearest Neighbors).
* KNNWithMeans: Алгоритм KNN, который учитывает средние рейтинги пользователей или предметов.
* KNNWithZScore: KNN алгоритм с нормализацией Z-оценок.
* KNNBaseline: KNN алгоритм с базовыми линиями (baseline).
* SVD: Алгоритм сингулярного разложения матрицы (Singular Value Decomposition).
* SVDpp: Улучшенная версия SVD, учитывающая дополнительные предпочтения пользователей.
* NMF: Негативное матричное факторизация (Non-negative Matrix Factorization).
* BaselineOnly: Базовый алгоритм для прогнозирования рейтингов.
* CoClustering: Алгоритм совместной кластеризации.

**Fraction of Concordant Pairs (FCP)** – это метрика для оценки качества предсказательных моделей, в частности, рекомендательных систем. FCP измеряет долю пар прогнозов, которые имеют правильный порядок относительно друг друга.  
Конкордантная пара – это пара, в которой предсказания модели соответствуют истинным рейтингам. Например, если у нас есть два товара и предсказание модели совпадает с фактическими рейтингами (более высокий рейтинг предсказан для товара с более высоким истинным рейтингом), это конкордантная пара.  
Эта метрика помогает понять, насколько хорошо модель предсказывает правильный порядок элементов, что важно для ранжирования в рекомендательных системах.  
Чем выше FCP, тем лучше модель в правильном упорядочивании элементов. Высокий FCP указывает на то, что модель делает больше правильных предсказаний порядка оценок, что очень важно для ранжирования в рекомендательных системах.

In [12]:
models = [KNNBasic(),
          KNNWithMeans(),
          KNNWithZScore(),
          KNNBaseline(),
          SVD(),
          SVDpp(),
          NMF(),
          BaselineOnly(),
          CoClustering()]
result_rmse = []
result_mae = []
result_fcp = []


for model in models:
    print(model)
    model.fit(trainset)
    test_pred = model.test(raw_testset)
    result_rmse.append(rmse(test_pred))
    result_mae.append(mae(test_pred))
    result_fcp.append(fcp(test_pred))


models_name = []
for i in range(len(models)):
    models_name.append(str(models[i]))


df_rez = pd.DataFrame(data=[models_name, result_rmse, result_mae, result_fcp]).T
df_rez.columns = ['model', 'rmse', 'mae', 'fcp']
df_rez

<surprise.prediction_algorithms.knns.KNNBasic object at 0x00000281A9BA0850>
Computing the msd similarity matrix...
Done computing similarity matrix.
RMSE: 0.9869
MAE:  0.9732
FCP:  0.0000
<surprise.prediction_algorithms.knns.KNNWithMeans object at 0x00000281A9BA0910>
Computing the msd similarity matrix...
Done computing similarity matrix.
RMSE: 0.9869
MAE:  0.9732
FCP:  0.0000
<surprise.prediction_algorithms.knns.KNNWithZScore object at 0x00000281A9BA0670>
Computing the msd similarity matrix...
Done computing similarity matrix.
RMSE: 0.9869
MAE:  0.9732
FCP:  0.0000
<surprise.prediction_algorithms.knns.KNNBaseline object at 0x00000281A9BA09D0>
Estimating biases using als...
Computing the msd similarity matrix...
Done computing similarity matrix.
RMSE: 0.9869
MAE:  0.9732
FCP:  0.0000
<surprise.prediction_algorithms.matrix_factorization.SVD object at 0x00000281A9BA0A30>
RMSE: 0.9869
MAE:  0.9732
FCP:  0.0000
<surprise.prediction_algorithms.matrix_factorization.SVDpp object at 0x00000281A9BA0A60>
RMSE: 0.9869
MAE:  0.9732
FCP:  0.0000
<surprise.prediction_algorithms.matrix_factorization.NMF object at 0x00000281A9BA0A90>
RMSE: 0.9869
MAE:  0.9732
FCP:  0.0000
<surprise.prediction_algorithms.baseline_only.BaselineOnly object at 0x00000281A9BA0AC0>
Estimating biases using als...
RMSE: 0.9869
MAE:  0.9732
FCP:  0.0000
<surprise.prediction_algorithms.co_clustering.CoClustering object at 0x00000281A9BA0B20>
RMSE: 0.9880
MAE:  0.9741
FCP:  0.3806

,model,rmse,mae,fcp
0,<surprise.prediction_algorithms.knns.KNNBasic ...,0.986888,0.973153,0.0
1,<surprise.prediction_algorithms.knns.KNNWithMe...,0.986888,0.973153,0.0
2,<surprise.prediction_algorithms.knns.KNNWithZS...,0.986888,0.973153,0.0
3,<surprise.prediction_algorithms.knns.KNNBaseli...,0.986888,0.973153,0.0
4,<surprise.prediction_algorithms.matrix_factori...,0.986888,0.973153,0.0
5,<surprise.prediction_algorithms.matrix_factori...,0.986888,0.973153,0.0
6,<surprise.prediction_algorithms.matrix_factori...,0.986888,0.973153,0.0
7,<surprise.prediction_algorithms.baseline_only....,0.986888,0.973153,0.0
8,<surprise.prediction_algorithms.co_clustering....,0.988028,0.974063,0.380597

Попробую использовать CoClustering модель и подобрать для нее наилучшие гиперпараметры.

In [13]:
def opt_Ext(trial):
    # задаем пространство поиска гиперпараметров

    n_cltr_u = trial.suggest_categorical('n_cltr_u',[3,4,5,6,7,8,9,10,11,12,13,14,15,17,20,25,30,])
    n_cltr_i = trial.suggest_categorical('n_cltr_i',[3,4,5,6,7,8,9,10,11,12,13,14,15,17,20,25,30,])
    n_epochs = trial.suggest_categorical('n_epochs',[10,15,20,25,30,35,])

    # создаем модель
    model = CoClustering(random_state=random_state,
                        verbose=0,
                        n_cltr_u=n_cltr_u,
                        n_cltr_i=n_cltr_i,
                        n_epochs=n_epochs,
                        )

    model.fit(trainset)
    test_pred = model.test(raw_testset)
    score = fcp(test_pred)
    return score

In [14]:
# cоздаем объект исследования
# можем напрямую указать, что нам необходимо минимизировать метрику direction="minimize"
stud = optuna.create_study(direction="maximize")


# ищем лучшую комбинацию гиперпараметров
stud.optimize(opt_Ext, n_trials=100)

[I 2024-10-18 20:42:45,439] A new study created in memory with name: no-name-ee6b3699-87f2-4ba5-b6ef-bfc76919e105
[I 2024-10-18 20:42:51,673] Trial 0 finished with value: 0.1998515314850079 and parameters: {'n_cltr_u': 10, 'n_cltr_i': 17, 'n_epochs': 10}. Best is trial 0 with value: 0.1998515314850079.

FCP:  0.1999

[I 2024-10-18 20:42:57,323] Trial 1 finished with value: 0.16857061379229363 and parameters: {'n_cltr_u': 11, 'n_cltr_i': 9, 'n_epochs': 10}. Best is trial 0 with value: 0.1998515314850079.

FCP:  0.1686

[I 2024-10-18 20:43:10,588] Trial 2 finished with value: 0.18979892103972537 and parameters: {'n_cltr_u': 4, 'n_cltr_i': 9, 'n_epochs': 35}. Best is trial 0 with value: 0.1998515314850079.

FCP:  0.1898

[I 2024-10-18 20:43:20,090] Trial 3 finished with value: 0.37280385078219014 and parameters: {'n_cltr_u': 14, 'n_cltr_i': 5, 'n_epochs': 20}. Best is trial 3 with value: 0.37280385078219014.

FCP:  0.3728

[I 2024-10-18 20:43:36,157] Trial 4 finished with value: 0.5641429301503198 and parameters: {'n_cltr_u': 30, 'n_cltr_i': 17, 'n_epochs': 25}. Best is trial 4 with value: 0.5641429301503198.

FCP:  0.5641

[I 2024-10-18 20:43:49,457] Trial 5 finished with value: 0.15776600081532816 and parameters: {'n_cltr_u': 6, 'n_cltr_i': 13, 'n_epochs': 30}. Best is trial 4 with value: 0.5641429301503198.

FCP:  0.1578

[I 2024-10-18 20:44:02,541] Trial 6 finished with value: 0.507914269532298 and parameters: {'n_cltr_u': 9, 'n_cltr_i': 11, 'n_epochs': 30}. Best is trial 4 with value: 0.5641429301503198.

FCP:  0.5079

[I 2024-10-18 20:44:13,108] Trial 7 finished with value: 0.515222115629344 and parameters: {'n_cltr_u': 3, 'n_cltr_i': 5, 'n_epochs': 30}. Best is trial 4 with value: 0.5641429301503198.

FCP:  0.5152

[I 2024-10-18 20:44:20,275] Trial 8 finished with value: 0.30431365945384636 and parameters: {'n_cltr_u': 25, 'n_cltr_i': 17, 'n_epochs': 10}. Best is trial 4 with value: 0.5641429301503198.

FCP:  0.3043

[I 2024-10-18 20:44:27,192] Trial 9 finished with value: 0.44542622846608604 and parameters: {'n_cltr_u': 12, 'n_cltr_i': 3, 'n_epochs': 15}. Best is trial 4 with value: 0.5641429301503198.

FCP:  0.4454

[I 2024-10-18 20:44:42,707] Trial 10 finished with value: 0.515222115629344 and parameters: {'n_cltr_u': 30, 'n_cltr_i': 12, 'n_epochs': 25}. Best is trial 4 with value: 0.5641429301503198.

FCP:  0.5152

[I 2024-10-18 20:44:51,775] Trial 11 finished with value: 0.6636269049513434 and parameters: {'n_cltr_u': 3, 'n_cltr_i': 5, 'n_epochs': 25}. Best is trial 11 with value: 0.6636269049513434.

FCP:  0.6636

[I 2024-10-18 20:45:01,779] Trial 12 finished with value: 0.15776600081532816 and parameters: {'n_cltr_u': 5, 'n_cltr_i': 8, 'n_epochs': 25}. Best is trial 11 with value: 0.6636269049513434.

FCP:  0.1578

[I 2024-10-18 20:45:14,227] Trial 13 finished with value: 0.15776600081532816 and parameters: {'n_cltr_u': 17, 'n_cltr_i': 10, 'n_epochs': 25}. Best is trial 11 with value: 0.6636269049513434.

FCP:  0.1578

[I 2024-10-18 20:45:23,877] Trial 14 finished with value: 0.0 and parameters: {'n_cltr_u': 7, 'n_cltr_i': 4, 'n_epochs': 25}. Best is trial 11 with value: 0.6636269049513434.

FCP:  0.0000

[I 2024-10-18 20:45:41,278] Trial 15 finished with value: 0.0 and parameters: {'n_cltr_u': 30, 'n_cltr_i': 25, 'n_epochs': 25}. Best is trial 11 with value: 0.6636269049513434.

FCP:  0.0000

[I 2024-10-18 20:45:50,111] Trial 16 finished with value: 0.1349559452150397 and parameters: {'n_cltr_u': 3, 'n_cltr_i': 30, 'n_epochs': 15}. Best is trial 11 with value: 0.6636269049513434.

FCP:  0.1350

[I 2024-10-18 20:46:08,331] Trial 17 finished with value: 0.0 and parameters: {'n_cltr_u': 13, 'n_cltr_i': 20, 'n_epochs': 35}. Best is trial 11 with value: 0.6636269049513434.

FCP:  0.0000

[I 2024-10-18 20:46:17,929] Trial 18 finished with value: 0.3845866998135488 and parameters: {'n_cltr_u': 8, 'n_cltr_i': 14, 'n_epochs': 20}. Best is trial 11 with value: 0.6636269049513434.

FCP:  0.3846

[I 2024-10-18 20:46:31,812] Trial 19 finished with value: 0.43523453955122304 and parameters: {'n_cltr_u': 20, 'n_cltr_i': 15, 'n_epochs': 25}. Best is trial 11 with value: 0.6636269049513434.

FCP:  0.4352

[I 2024-10-18 20:46:43,391] Trial 20 finished with value: 0.0 and parameters: {'n_cltr_u': 15, 'n_cltr_i': 7, 'n_epochs': 25}. Best is trial 11 with value: 0.6636269049513434.

FCP:  0.0000

[I 2024-10-18 20:46:53,992] Trial 21 finished with value: 0.515222115629344 and parameters: {'n_cltr_u': 3, 'n_cltr_i': 5, 'n_epochs': 30}. Best is trial 11 with value: 0.6636269049513434.

FCP:  0.5152

[I 2024-10-18 20:47:04,463] Trial 22 finished with value: 0.515222115629344 and parameters: {'n_cltr_u': 3, 'n_cltr_i': 5, 'n_epochs': 30}. Best is trial 11 with value: 0.6636269049513434.

FCP:  0.5152

[I 2024-10-18 20:47:15,297] Trial 23 finished with value: 0.4402890642951226 and parameters: {'n_cltr_u': 3, 'n_cltr_i': 6, 'n_epochs': 30}. Best is trial 11 with value: 0.6636269049513434.

FCP:  0.4403

[I 2024-10-18 20:47:29,248] Trial 24 finished with value: 0.7502800230072958 and parameters: {'n_cltr_u': 30, 'n_cltr_i': 5, 'n_epochs': 25}. Best is trial 24 with value: 0.7502800230072958.

FCP:  0.7503

[I 2024-10-18 20:47:45,198] Trial 25 finished with value: 0.5641429301503198 and parameters: {'n_cltr_u': 30, 'n_cltr_i': 17, 'n_epochs': 25}. Best is trial 24 with value: 0.7502800230072958.

FCP:  0.5641

[I 2024-10-18 20:47:59,198] Trial 26 finished with value: 0.7502800230072958 and parameters: {'n_cltr_u': 30, 'n_cltr_i': 5, 'n_epochs': 25}. Best is trial 24 with value: 0.7502800230072958.

FCP:  0.7503

[I 2024-10-18 20:48:13,034] Trial 27 finished with value: 0.7502800230072958 and parameters: {'n_cltr_u': 30, 'n_cltr_i': 5, 'n_epochs': 25}. Best is trial 24 with value: 0.7502800230072958.

FCP:  0.7503

[I 2024-10-18 20:48:27,433] Trial 28 finished with value: 0.7502800230072958 and parameters: {'n_cltr_u': 30, 'n_cltr_i': 5, 'n_epochs': 25}. Best is trial 24 with value: 0.7502800230072958.

FCP:  0.7503

[I 2024-10-18 20:48:34,416] Trial 29 finished with value: 0.4369675971243985 and parameters: {'n_cltr_u': 10, 'n_cltr_i': 5, 'n_epochs': 15}. Best is trial 24 with value: 0.7502800230072958.

FCP:  0.4370

[I 2024-10-18 20:48:46,017] Trial 30 finished with value: 0.39637135123271633 and parameters: {'n_cltr_u': 30, 'n_cltr_i': 6, 'n_epochs': 20}. Best is trial 24 with value: 0.7502800230072958.

FCP:  0.3964

[I 2024-10-18 20:49:00,069] Trial 31 finished with value: 0.7502800230072958 and parameters: {'n_cltr_u': 30, 'n_cltr_i': 5, 'n_epochs': 25}. Best is trial 24 with value: 0.7502800230072958.

FCP:  0.7503

[I 2024-10-18 20:49:06,704] Trial 32 finished with value: 0.8143141451691637 and parameters: {'n_cltr_u': 30, 'n_cltr_i': 5, 'n_epochs': 10}. Best is trial 32 with value: 0.8143141451691637.

FCP:  0.8143

[I 2024-10-18 20:49:13,301] Trial 33 finished with value: 0.8143141451691637 and parameters: {'n_cltr_u': 30, 'n_cltr_i': 5, 'n_epochs': 10}. Best is trial 32 with value: 0.8143141451691637.

FCP:  0.8143

[I 2024-10-18 20:49:21,751] Trial 34 finished with value: 0.1349559452150397 and parameters: {'n_cltr_u': 30, 'n_cltr_i': 30, 'n_epochs': 10}. Best is trial 32 with value: 0.8143141451691637.

FCP:  0.1350

[I 2024-10-18 20:49:27,302] Trial 35 finished with value: 0.16857061379229363 and parameters: {'n_cltr_u': 11, 'n_cltr_i': 9, 'n_epochs': 10}. Best is trial 32 with value: 0.8143141451691637.

FCP:  0.1686

[I 2024-10-18 20:49:32,668] Trial 36 finished with value: 0.3845866998135488 and parameters: {'n_cltr_u': 4, 'n_cltr_i': 13, 'n_epochs': 10}. Best is trial 32 with value: 0.8143141451691637.

FCP:  0.3846

[I 2024-10-18 20:49:38,637] Trial 37 finished with value: 0.15776600081532816 and parameters: {'n_cltr_u': 9, 'n_cltr_i': 11, 'n_epochs': 10}. Best is trial 32 with value: 0.8143141451691637.

FCP:  0.1578

[I 2024-10-18 20:49:43,719] Trial 38 finished with value: 0.6597557121855379 and parameters: {'n_cltr_u': 6, 'n_cltr_i': 5, 'n_epochs': 10}. Best is trial 32 with value: 0.8143141451691637.

FCP:  0.6598

[I 2024-10-18 20:49:58,102] Trial 39 finished with value: 0.15776600081532816 and parameters: {'n_cltr_u': 14, 'n_cltr_i': 3, 'n_epochs': 35}. Best is trial 32 with value: 0.8143141451691637.

FCP:  0.1578

[I 2024-10-18 20:50:04,953] Trial 40 finished with value: 0.7898024219247929 and parameters: {'n_cltr_u': 25, 'n_cltr_i': 14, 'n_epochs': 10}. Best is trial 32 with value: 0.8143141451691637.

FCP:  0.7898

[I 2024-10-18 20:50:11,919] Trial 41 finished with value: 0.7898024219247929 and parameters: {'n_cltr_u': 25, 'n_cltr_i': 14, 'n_epochs': 10}. Best is trial 32 with value: 0.8143141451691637.

FCP:  0.7898

[I 2024-10-18 20:50:18,886] Trial 42 finished with value: 0.7898024219247929 and parameters: {'n_cltr_u': 25, 'n_cltr_i': 14, 'n_epochs': 10}. Best is trial 32 with value: 0.8143141451691637.

FCP:  0.7898

[I 2024-10-18 20:50:25,787] Trial 43 finished with value: 0.7898024219247929 and parameters: {'n_cltr_u': 25, 'n_cltr_i': 14, 'n_epochs': 10}. Best is trial 32 with value: 0.8143141451691637.

FCP:  0.7898

[I 2024-10-18 20:50:32,770] Trial 44 finished with value: 0.7898024219247929 and parameters: {'n_cltr_u': 25, 'n_cltr_i': 14, 'n_epochs': 10}. Best is trial 32 with value: 0.8143141451691637.

FCP:  0.7898

[I 2024-10-18 20:50:40,159] Trial 45 finished with value: 0.7898024219247929 and parameters: {'n_cltr_u': 25, 'n_cltr_i': 14, 'n_epochs': 10}. Best is trial 32 with value: 0.8143141451691637.

FCP:  0.7898

[I 2024-10-18 20:50:47,020] Trial 46 finished with value: 0.7898024219247929 and parameters: {'n_cltr_u': 25, 'n_cltr_i': 14, 'n_epochs': 10}. Best is trial 32 with value: 0.8143141451691637.

FCP:  0.7898

[I 2024-10-18 20:50:53,837] Trial 47 finished with value: 0.6523478627079384 and parameters: {'n_cltr_u': 25, 'n_cltr_i': 12, 'n_epochs': 10}. Best is trial 32 with value: 0.8143141451691637.

FCP:  0.6523

[I 2024-10-18 20:50:59,287] Trial 48 finished with value: 0.16857061379229363 and parameters: {'n_cltr_u': 5, 'n_cltr_i': 14, 'n_epochs': 10}. Best is trial 32 with value: 0.8143141451691637.

FCP:  0.1686

[I 2024-10-18 20:51:04,909] Trial 49 finished with value: 0.3556491167151352 and parameters: {'n_cltr_u': 12, 'n_cltr_i': 8, 'n_epochs': 10}. Best is trial 32 with value: 0.8143141451691637.

FCP:  0.3556

[I 2024-10-18 20:51:10,305] Trial 50 finished with value: 0.44181065257746677 and parameters: {'n_cltr_u': 7, 'n_cltr_i': 10, 'n_epochs': 10}. Best is trial 32 with value: 0.8143141451691637.

FCP:  0.4418

[I 2024-10-18 20:51:17,238] Trial 51 finished with value: 0.7898024219247929 and parameters: {'n_cltr_u': 25, 'n_cltr_i': 14, 'n_epochs': 10}. Best is trial 32 with value: 0.8143141451691637.

FCP:  0.7898

[I 2024-10-18 20:51:24,140] Trial 52 finished with value: 0.7898024219247929 and parameters: {'n_cltr_u': 25, 'n_cltr_i': 14, 'n_epochs': 10}. Best is trial 32 with value: 0.8143141451691637.

FCP:  0.7898

[I 2024-10-18 20:51:30,372] Trial 53 finished with value: 0.571202360035574 and parameters: {'n_cltr_u': 25, 'n_cltr_i': 4, 'n_epochs': 10}. Best is trial 32 with value: 0.8143141451691637.

FCP:  0.5712

[I 2024-10-18 20:51:37,725] Trial 54 finished with value: 0.49626506576233903 and parameters: {'n_cltr_u': 17, 'n_cltr_i': 25, 'n_epochs': 10}. Best is trial 32 with value: 0.8143141451691637.

FCP:  0.4963

[I 2024-10-18 20:51:55,889] Trial 55 finished with value: 0.0 and parameters: {'n_cltr_u': 13, 'n_cltr_i': 20, 'n_epochs': 35}. Best is trial 32 with value: 0.8143141451691637.

FCP:  0.0000

[I 2024-10-18 20:52:07,889] Trial 56 finished with value: 0.3114026236125126 and parameters: {'n_cltr_u': 25, 'n_cltr_i': 14, 'n_epochs': 20}. Best is trial 32 with value: 0.8143141451691637.

FCP:  0.3114

[I 2024-10-18 20:52:13,659] Trial 57 finished with value: 0.23800738007380076 and parameters: {'n_cltr_u': 8, 'n_cltr_i': 15, 'n_epochs': 10}. Best is trial 32 with value: 0.8143141451691637.

FCP:  0.2380

[I 2024-10-18 20:52:21,926] Trial 58 finished with value: 0.0 and parameters: {'n_cltr_u': 20, 'n_cltr_i': 7, 'n_epochs': 15}. Best is trial 32 with value: 0.8143141451691637.

FCP:  0.0000

[I 2024-10-18 20:52:28,090] Trial 59 finished with value: 0.44823589720730156 and parameters: {'n_cltr_u': 15, 'n_cltr_i': 14, 'n_epochs': 10}. Best is trial 32 with value: 0.8143141451691637.

FCP:  0.4482

[I 2024-10-18 20:52:33,976] Trial 60 finished with value: 0.1998515314850079 and parameters: {'n_cltr_u': 10, 'n_cltr_i': 14, 'n_epochs': 10}. Best is trial 32 with value: 0.8143141451691637.

FCP:  0.1999

[I 2024-10-18 20:52:41,441] Trial 61 finished with value: 0.7898024219247929 and parameters: {'n_cltr_u': 25, 'n_cltr_i': 14, 'n_epochs': 10}. Best is trial 32 with value: 0.8143141451691637.

FCP:  0.7898

[I 2024-10-18 20:52:48,391] Trial 62 finished with value: 0.7898024219247929 and parameters: {'n_cltr_u': 25, 'n_cltr_i': 14, 'n_epochs': 10}. Best is trial 32 with value: 0.8143141451691637.

FCP:  0.7898

[I 2024-10-18 20:52:55,008] Trial 63 finished with value: 0.6597557121855379 and parameters: {'n_cltr_u': 25, 'n_cltr_i': 9, 'n_epochs': 10}. Best is trial 32 with value: 0.8143141451691637.

FCP:  0.6598

[I 2024-10-18 20:53:00,324] Trial 64 finished with value: 0.3845866998135488 and parameters: {'n_cltr_u': 4, 'n_cltr_i': 13, 'n_epochs': 10}. Best is trial 32 with value: 0.8143141451691637.

FCP:  0.3846

[I 2024-10-18 20:53:06,311] Trial 65 finished with value: 0.30431365945384636 and parameters: {'n_cltr_u': 11, 'n_cltr_i': 14, 'n_epochs': 10}. Best is trial 32 with value: 0.8143141451691637.

FCP:  0.3043

[I 2024-10-18 20:53:12,992] Trial 66 finished with value: 0.5828445789026784 and parameters: {'n_cltr_u': 25, 'n_cltr_i': 11, 'n_epochs': 10}. Best is trial 32 with value: 0.8143141451691637.

FCP:  0.5828

[I 2024-10-18 20:53:21,892] Trial 67 finished with value: 0.1722237684386307 and parameters: {'n_cltr_u': 14, 'n_cltr_i': 3, 'n_epochs': 20}. Best is trial 32 with value: 0.8143141451691637.

FCP:  0.1722

[I 2024-10-18 20:53:30,026] Trial 68 finished with value: 0.4545154063682104 and parameters: {'n_cltr_u': 9, 'n_cltr_i': 17, 'n_epochs': 15}. Best is trial 32 with value: 0.8143141451691637.

FCP:  0.4545

[I 2024-10-18 20:53:44,843] Trial 69 finished with value: 0.3040999719180006 and parameters: {'n_cltr_u': 6, 'n_cltr_i': 12, 'n_epochs': 35}. Best is trial 32 with value: 0.8143141451691637.

FCP:  0.3041

[I 2024-10-18 20:54:05,227] Trial 70 finished with value: 0.0 and parameters: {'n_cltr_u': 25, 'n_cltr_i': 30, 'n_epochs': 30}. Best is trial 32 with value: 0.8143141451691637.

FCP:  0.0000

[I 2024-10-18 20:54:12,343] Trial 71 finished with value: 0.7898024219247929 and parameters: {'n_cltr_u': 25, 'n_cltr_i': 14, 'n_epochs': 10}. Best is trial 32 with value: 0.8143141451691637.

FCP:  0.7898

[I 2024-10-18 20:54:19,210] Trial 72 finished with value: 0.7898024219247929 and parameters: {'n_cltr_u': 25, 'n_cltr_i': 14, 'n_epochs': 10}. Best is trial 32 with value: 0.8143141451691637.

FCP:  0.7898

[I 2024-10-18 20:54:24,746] Trial 73 finished with value: 0.16857061379229363 and parameters: {'n_cltr_u': 5, 'n_cltr_i': 14, 'n_epochs': 10}. Best is trial 32 with value: 0.8143141451691637.

FCP:  0.1686

[I 2024-10-18 20:54:30,311] Trial 74 finished with value: 0.3556491167151352 and parameters: {'n_cltr_u': 12, 'n_cltr_i': 8, 'n_epochs': 10}. Best is trial 32 with value: 0.8143141451691637.

FCP:  0.3556

[I 2024-10-18 20:54:36,911] Trial 75 finished with value: 0.0 and parameters: {'n_cltr_u': 25, 'n_cltr_i': 10, 'n_epochs': 10}. Best is trial 32 with value: 0.8143141451691637.

FCP:  0.0000

[I 2024-10-18 20:54:42,595] Trial 76 finished with value: 0.48836081306277435 and parameters: {'n_cltr_u': 17, 'n_cltr_i': 4, 'n_epochs': 10}. Best is trial 32 with value: 0.8143141451691637.

FCP:  0.4884

[I 2024-10-18 20:54:48,195] Trial 77 finished with value: 0.45987094744843793 and parameters: {'n_cltr_u': 7, 'n_cltr_i': 14, 'n_epochs': 10}. Best is trial 32 with value: 0.8143141451691637.

FCP:  0.4599

[I 2024-10-18 20:54:53,294] Trial 78 finished with value: 0.6053049213273468 and parameters: {'n_cltr_u': 8, 'n_cltr_i': 6, 'n_epochs': 10}. Best is trial 32 with value: 0.8143141451691637.

FCP:  0.6053

[I 2024-10-18 20:55:11,862] Trial 79 finished with value: 0.23784615384615385 and parameters: {'n_cltr_u': 20, 'n_cltr_i': 25, 'n_epochs': 30}. Best is trial 32 with value: 0.8143141451691637.

FCP:  0.2378

[I 2024-10-18 20:55:19,129] Trial 80 finished with value: 0.11107525725144311 and parameters: {'n_cltr_u': 25, 'n_cltr_i': 20, 'n_epochs': 10}. Best is trial 32 with value: 0.8143141451691637.

FCP:  0.1111

[I 2024-10-18 20:55:26,062] Trial 81 finished with value: 0.7898024219247929 and parameters: {'n_cltr_u': 25, 'n_cltr_i': 14, 'n_epochs': 10}. Best is trial 32 with value: 0.8143141451691637.

FCP:  0.7898

[I 2024-10-18 20:55:32,931] Trial 82 finished with value: 0.7898024219247929 and parameters: {'n_cltr_u': 25, 'n_cltr_i': 14, 'n_epochs': 10}. Best is trial 32 with value: 0.8143141451691637.

FCP:  0.7898

[I 2024-10-18 20:55:40,295] Trial 83 finished with value: 0.515222115629344 and parameters: {'n_cltr_u': 30, 'n_cltr_i': 14, 'n_epochs': 10}. Best is trial 32 with value: 0.8143141451691637.

FCP:  0.5152

[I 2024-10-18 20:55:46,399] Trial 84 finished with value: 0.515222115629344 and parameters: {'n_cltr_u': 13, 'n_cltr_i': 15, 'n_epochs': 10}. Best is trial 32 with value: 0.8143141451691637.

FCP:  0.5152

[I 2024-10-18 20:55:52,680] Trial 85 finished with value: 0.6597557121855379 and parameters: {'n_cltr_u': 25, 'n_cltr_i': 5, 'n_epochs': 10}. Best is trial 32 with value: 0.8143141451691637.

FCP:  0.6598

[I 2024-10-18 20:56:03,747] Trial 86 finished with value: 0.0 and parameters: {'n_cltr_u': 25, 'n_cltr_i': 7, 'n_epochs': 20}. Best is trial 32 with value: 0.8143141451691637.

FCP:  0.0000

[I 2024-10-18 20:56:09,928] Trial 87 finished with value: 0.44823589720730156 and parameters: {'n_cltr_u': 15, 'n_cltr_i': 14, 'n_epochs': 10}. Best is trial 32 with value: 0.8143141451691637.

FCP:  0.4482

[I 2024-10-18 20:56:25,848] Trial 88 finished with value: 0.09426379247351115 and parameters: {'n_cltr_u': 10, 'n_cltr_i': 14, 'n_epochs': 35}. Best is trial 32 with value: 0.8143141451691637.

FCP:  0.0943

[I 2024-10-18 20:56:34,965] Trial 89 finished with value: 0.7502800230072958 and parameters: {'n_cltr_u': 30, 'n_cltr_i': 5, 'n_epochs': 15}. Best is trial 32 with value: 0.8143141451691637.

FCP:  0.7503

[I 2024-10-18 20:56:41,882] Trial 90 finished with value: 0.7898024219247929 and parameters: {'n_cltr_u': 25, 'n_cltr_i': 14, 'n_epochs': 10}. Best is trial 32 with value: 0.8143141451691637.

FCP:  0.7898

[I 2024-10-18 20:56:48,732] Trial 91 finished with value: 0.7898024219247929 and parameters: {'n_cltr_u': 25, 'n_cltr_i': 14, 'n_epochs': 10}. Best is trial 32 with value: 0.8143141451691637.

FCP:  0.7898

[I 2024-10-18 20:56:55,682] Trial 92 finished with value: 0.7898024219247929 and parameters: {'n_cltr_u': 25, 'n_cltr_i': 14, 'n_epochs': 10}. Best is trial 32 with value: 0.8143141451691637.

FCP:  0.7898

[I 2024-10-18 20:57:02,216] Trial 93 finished with value: 0.6597557121855379 and parameters: {'n_cltr_u': 25, 'n_cltr_i': 9, 'n_epochs': 10}. Best is trial 32 with value: 0.8143141451691637.

FCP:  0.6598

[I 2024-10-18 20:57:08,199] Trial 94 finished with value: 0.30431365945384636 and parameters: {'n_cltr_u': 11, 'n_cltr_i': 14, 'n_epochs': 10}. Best is trial 32 with value: 0.8143141451691637.

FCP:  0.3043

[I 2024-10-18 20:57:13,517] Trial 95 finished with value: 0.3845866998135488 and parameters: {'n_cltr_u': 4, 'n_cltr_i': 13, 'n_epochs': 10}. Best is trial 32 with value: 0.8143141451691637.

FCP:  0.3846

[I 2024-10-18 20:57:19,817] Trial 96 finished with value: 0.48403256105197245 and parameters: {'n_cltr_u': 14, 'n_cltr_i': 17, 'n_epochs': 10}. Best is trial 32 with value: 0.8143141451691637.

FCP:  0.4840

[I 2024-10-18 20:57:27,400] Trial 97 finished with value: 0.7898024219247929 and parameters: {'n_cltr_u': 25, 'n_cltr_i': 14, 'n_epochs': 10}. Best is trial 32 with value: 0.8143141451691637.

FCP:  0.7898

[I 2024-10-18 20:57:32,150] Trial 98 finished with value: 0.5080861729426509 and parameters: {'n_cltr_u': 6, 'n_cltr_i': 3, 'n_epochs': 10}. Best is trial 32 with value: 0.8143141451691637.

FCP:  0.5081

[I 2024-10-18 20:57:39,267] Trial 99 finished with value: 0.6597557121855379 and parameters: {'n_cltr_u': 30, 'n_cltr_i': 12, 'n_epochs': 10}. Best is trial 32 with value: 0.8143141451691637.

FCP:  0.6598

In [15]:
print(stud.best_params)

{'n_cltr_u': 30, 'n_cltr_i': 5, 'n_epochs': 10}

In [16]:
best_model_surprise = CoClustering(random_state=random_state,
                        verbose=0,
                        n_cltr_u=stud.best_params['n_cltr_u'],
                        n_cltr_i=stud.best_params['n_cltr_i'],
                        n_epochs=stud.best_params['n_epochs'],
                        )

best_model_surprise.fit(trainset)


# # Производим сериализацию и записываем результат в файл формата pkl
with open(r'models\best_model_surprise.pkl', 'wb') as output:
    pickle.dump(best_model_surprise, output)

In [17]:
fig = optuna.visualization.plot_param_importances(stud)
fig.show()

In [22]:

fig = optuna.visualization.plot_contour(stud,)
fig