In [1]:
from surprise import  KNNBasic,KNNWithMeans,KNNWithZScore,KNNBaseline,SVD,SVDpp,NMF,BaselineOnly,CoClustering

from surprise import Dataset
from surprise.accuracy import rmse, mae, fcp
from surprise import Reader

import pandas as pd
import pickle
from collections import defaultdict

from function import get_top_n
import optuna

In [2]:
random_state=42

import random
import numpy as np

my_seed = 42
random.seed(my_seed)
np.random.seed(my_seed)

Surprise используется в различных областях для построения и оценки рекомендательных систем. Вот некоторые из них:

* Электронная коммерция: Рекомендации товаров и услуг на основе предыдущих покупок и просмотров пользователей.
* Платформы потокового вещания: Рекомендации фильмов, сериалов и музыки на основе предпочтений пользователей и их взаимодействий.
* Социальные сети: Персонализированные рекомендации друзей, групп и контента.
* Образование: Рекомендации курсов и учебных материалов на основе прошлых успехов и интересов студентов.
* Новости и контент: Рекомендации новостных статей и других информационных материалов на основе предпочтений пользователей.

Surprise помогает создавать точные и персонализированные рекомендации, улучшая опыт пользователей в различных сферах.

In [3]:
# # # Производим десериализацию и извлекаем из файла формата pkl
with open('data/train_time.pkl', 'rb') as pkl_file:
    train = pickle.load(pkl_file)

with open('data/test_time.pkl', 'rb') as pkl_file:
    test = pickle.load(pkl_file)

In [4]:
train = train.sample(frac=0.13, random_state=random_state)

In [5]:
train = train.groupby(['visitorid','itemid'],as_index=False)['event'].sum()
test = test.groupby(['visitorid','itemid'],as_index=False)['event'].sum()

In [6]:
train = train[["itemid", "visitorid", "event"]].rename(columns={"itemid": "iid","visitorid": "uid",'event':'r_ui'})
test = test[["itemid", "visitorid", "event"]].rename(columns={"itemid": "iid","visitorid": "uid",'event':'r_ui'})

In [7]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108093 entries, 0 to 108092
Data columns (total 3 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   iid     108093 non-null  int64
 1   uid     108093 non-null  int64
 2   r_ui    108093 non-null  int64
dtypes: int64(3)
memory usage: 2.5 MB

In [8]:
train

          iid      uid  r_ui
0       57171       74     1
1      257575       75     2
2      400946       97     2
3       10034      172     2
4      374400      172     1
...       ...      ...   ...
58099  107832  1407512     2
58100  118079  1407512     1
58101  241408  1407512     2
58102  441579  1407512     1
58103   13961  1407573     1

[58104 rows x 3 columns]

In [9]:
test.r_ui.max()

219

Классы в surprise принимают данные через свой отдельный класс Dataset, в который мы отправляем данные и класс Reader с указанным диапазоном допустимых оценок:

In [10]:
# Создание Reader и Dataset
reader = Reader(rating_scale=(1, 300))
train_data = Dataset.load_from_df(train[['uid', 'iid', 'r_ui']], reader)
test_data = Dataset.load_from_df(test[['uid', 'iid', 'r_ui']], reader)

# Создание полного тренировочного набора
trainset = train_data.build_full_trainset()

# Преобразование тестового набора в формат списков кортежей
raw_testset = [(uid, iid, r_ui) for (uid, iid, r_ui) in zip(test['uid'], test['iid'], test['r_ui'])]

Виды моделей в библиотеке surprise
* KNNBasic: Простой алгоритм ближайших соседей (K-Nearest Neighbors).
* KNNWithMeans: Алгоритм KNN, который учитывает средние рейтинги пользователей или предметов.
* KNNWithZScore: KNN алгоритм с нормализацией Z-оценок.
* KNNBaseline: KNN алгоритм с базовыми линиями (baseline).
* SVD: Алгоритм сингулярного разложения матрицы (Singular Value Decomposition).
* SVDpp: Улучшенная версия SVD, учитывающая дополнительные предпочтения пользователей.
* NMF: Негативное матричное факторизация (Non-negative Matrix Factorization).
* BaselineOnly: Базовый алгоритм для прогнозирования рейтингов.
* CoClustering: Алгоритм совместной кластеризации.

**Fraction of Concordant Pairs (FCP)** – это метрика для оценки качества предсказательных моделей, в частности, рекомендательных систем. FCP измеряет долю пар прогнозов, которые имеют правильный порядок относительно друг друга.  
Конкордантная пара – это пара, в которой предсказания модели соответствуют истинным рейтингам. Например, если у нас есть два товара и предсказание модели совпадает с фактическими рейтингами (более высокий рейтинг предсказан для товара с более высоким истинным рейтингом), это конкордантная пара.  
Эта метрика помогает понять, насколько хорошо модель предсказывает правильный порядок элементов, что важно для ранжирования в рекомендательных системах.  
Чем выше FCP, тем лучше модель в правильном упорядочивании элементов. Высокий FCP указывает на то, что модель делает больше правильных предсказаний порядка оценок, что очень важно для ранжирования в рекомендательных системах.

In [11]:
models = [
          KNNBasic(random_state=random_state),
          KNNWithMeans(random_state=random_state),
          KNNWithZScore(random_state=random_state),
          KNNBaseline(random_state=random_state),
          SVD(random_state=random_state),
          SVDpp(random_state=random_state),
          NMF(random_state=random_state),
          BaselineOnly(),
          CoClustering(random_state=random_state)
        ]
result_rmse = []
result_mae = []
result_fcp = []


for model in models:
    print(model)
    model.fit(trainset)
    test_pred = model.test(raw_testset)
    result_rmse.append(rmse(test_pred))
    result_mae.append(mae(test_pred))
    result_fcp.append(fcp(test_pred))


models_name = []
for i in range(len(models)):
    models_name.append(str(models[i]))


df_rez = pd.DataFrame(data=[models_name, result_rmse, result_mae, result_fcp]).T
df_rez.columns = ['model', 'rmse', 'mae', 'fcp']
df_rez

<surprise.prediction_algorithms.knns.KNNBasic object at 0x000001A1EB6C1CD0>
Computing the msd similarity matrix...
Done computing similarity matrix.
RMSE: 2.8092
MAE:  1.0966
FCP:  0.2431
<surprise.prediction_algorithms.knns.KNNWithMeans object at 0x000001A1EB6C1D30>
Computing the msd similarity matrix...
Done computing similarity matrix.
RMSE: 2.8149
MAE:  1.0942
FCP:  0.4070
<surprise.prediction_algorithms.knns.KNNWithZScore object at 0x000001A1EB6C1DF0>
Computing the msd similarity matrix...
Done computing similarity matrix.
RMSE: 2.8148
MAE:  1.0943
FCP:  0.4076
<surprise.prediction_algorithms.knns.KNNBaseline object at 0x000001A1EB6C1DC0>
Estimating biases using als...
Computing the msd similarity matrix...
Done computing similarity matrix.
RMSE: 2.8046
MAE:  1.0914
FCP:  0.4320
<surprise.prediction_algorithms.matrix_factorization.SVD object at 0x000001A1EB6C1E50>
RMSE: 2.8164
MAE:  1.0908
FCP:  0.4324
<surprise.prediction_algorithms.matrix_factorization.SVDpp object at 0x000001A1EB6C1EB0>
RMSE: 2.8163
MAE:  1.0891
FCP:  0.4337
<surprise.prediction_algorithms.matrix_factorization.NMF object at 0x000001A1EB6C1EE0>
RMSE: 2.8146
MAE:  1.0900
FCP:  0.4458
<surprise.prediction_algorithms.baseline_only.BaselineOnly object at 0x000001A1EB6C1F10>
Estimating biases using als...
RMSE: 2.8229
MAE:  1.0918
FCP:  0.4328
<surprise.prediction_algorithms.co_clustering.CoClustering object at 0x000001A1EB6C1F70>
RMSE: 2.8050
MAE:  1.1028
FCP:  0.4519

,model,rmse,mae,fcp
0,<surprise.prediction_algorithms.knns.KNNBasic ...,2.80917,1.096589,0.243063
1,<surprise.prediction_algorithms.knns.KNNWithMe...,2.814862,1.094241,0.407004
2,<surprise.prediction_algorithms.knns.KNNWithZS...,2.814826,1.094287,0.407626
3,<surprise.prediction_algorithms.knns.KNNBaseli...,2.804612,1.091398,0.431981
4,<surprise.prediction_algorithms.matrix_factori...,2.816423,1.090808,0.432388
5,<surprise.prediction_algorithms.matrix_factori...,2.816292,1.089111,0.43368
6,<surprise.prediction_algorithms.matrix_factori...,2.814564,1.090035,0.445773
7,<surprise.prediction_algorithms.baseline_only....,2.822889,1.091832,0.432778
8,<surprise.prediction_algorithms.co_clustering....,2.80496,1.102799,0.451891

In [13]:
# Получим топ рекомендаций для visitorid == 2
uid = 2
get_top_n(test_pred,10)[uid]

[216305, 259884, 325215, 342816]

Попробую использовать CoClustering модель и подобрать для нее наилучшие гиперпараметры.

In [14]:
def opt_Ext(trial):
    # задаем пространство поиска гиперпараметров

    n_cltr_u = trial.suggest_categorical('n_cltr_u',[3,4,5,6,7,8,9,10,11,12,13,14,15,17,20,25,30,])
    n_cltr_i = trial.suggest_categorical('n_cltr_i',[3,4,5,6,7,8,9,10,11,12,13,14,15,17,20,25,30,])
    n_epochs = trial.suggest_categorical('n_epochs',[10,15,20,25,30,35,])

    # создаем модель
    model = CoClustering(random_state=random_state,
                        verbose=0,
                        n_cltr_u=n_cltr_u,
                        n_cltr_i=n_cltr_i,
                        n_epochs=n_epochs,
                        )

    model.fit(trainset)
    test_pred = model.test(raw_testset)
    score = fcp(test_pred)
    return score

In [15]:
# cоздаем объект исследования
# можем напрямую указать, что нам необходимо минимизировать метрику direction="minimize"
stud = optuna.create_study(direction="maximize")


# ищем лучшую комбинацию гиперпараметров
stud.optimize(opt_Ext, n_trials=150)

[I 2024-10-23 13:05:53,490] A new study created in memory with name: no-name-23a9e5ae-abc0-41de-bc9b-44ca4b64f139
[I 2024-10-23 13:06:02,828] Trial 0 finished with value: 0.4445740586651438 and parameters: {'n_cltr_u': 9, 'n_cltr_i': 25, 'n_epochs': 15}. Best is trial 0 with value: 0.4445740586651438.

FCP:  0.4446

[I 2024-10-23 13:06:14,666] Trial 1 finished with value: 0.4503001484540726 and parameters: {'n_cltr_u': 6, 'n_cltr_i': 6, 'n_epochs': 30}. Best is trial 1 with value: 0.4503001484540726.

FCP:  0.4503

[I 2024-10-23 13:06:19,871] Trial 2 finished with value: 0.4452897455865846 and parameters: {'n_cltr_u': 10, 'n_cltr_i': 3, 'n_epochs': 10}. Best is trial 1 with value: 0.4503001484540726.

FCP:  0.4453

[I 2024-10-23 13:06:27,520] Trial 3 finished with value: 0.44886578409564365 and parameters: {'n_cltr_u': 14, 'n_cltr_i': 5, 'n_epochs': 15}. Best is trial 1 with value: 0.4503001484540726.

FCP:  0.4489

[I 2024-10-23 13:06:33,979] Trial 4 finished with value: 0.4533136746153807 and parameters: {'n_cltr_u': 6, 'n_cltr_i': 3, 'n_epochs': 15}. Best is trial 4 with value: 0.4533136746153807.

FCP:  0.4533

[I 2024-10-23 13:06:48,370] Trial 5 finished with value: 0.44858207623373225 and parameters: {'n_cltr_u': 20, 'n_cltr_i': 14, 'n_epochs': 25}. Best is trial 4 with value: 0.4533136746153807.

FCP:  0.4486

[I 2024-10-23 13:06:56,346] Trial 6 finished with value: 0.4470812954363426 and parameters: {'n_cltr_u': 15, 'n_cltr_i': 7, 'n_epochs': 15}. Best is trial 4 with value: 0.4533136746153807.

FCP:  0.4471

[I 2024-10-23 13:07:02,336] Trial 7 finished with value: 0.44266284875868267 and parameters: {'n_cltr_u': 6, 'n_cltr_i': 17, 'n_epochs': 10}. Best is trial 4 with value: 0.4533136746153807.

FCP:  0.4427

[I 2024-10-23 13:07:18,135] Trial 8 finished with value: 0.4446715339011431 and parameters: {'n_cltr_u': 12, 'n_cltr_i': 15, 'n_epochs': 30}. Best is trial 4 with value: 0.4533136746153807.

FCP:  0.4447

[I 2024-10-23 13:07:35,352] Trial 9 finished with value: 0.44916054968474217 and parameters: {'n_cltr_u': 12, 'n_cltr_i': 15, 'n_epochs': 35}. Best is trial 4 with value: 0.4533136746153807.

FCP:  0.4492

[I 2024-10-23 13:07:46,270] Trial 10 finished with value: 0.44790273738231273 and parameters: {'n_cltr_u': 25, 'n_cltr_i': 3, 'n_epochs': 20}. Best is trial 4 with value: 0.4533136746153807.

FCP:  0.4479

[I 2024-10-23 13:07:58,001] Trial 11 finished with value: 0.4503001484540726 and parameters: {'n_cltr_u': 6, 'n_cltr_i': 6, 'n_epochs': 30}. Best is trial 4 with value: 0.4533136746153807.

FCP:  0.4503

[I 2024-10-23 13:08:09,904] Trial 12 finished with value: 0.44683456552158446 and parameters: {'n_cltr_u': 3, 'n_cltr_i': 10, 'n_epochs': 30}. Best is trial 4 with value: 0.4533136746153807.

FCP:  0.4468

[I 2024-10-23 13:08:21,104] Trial 13 finished with value: 0.4476048188805265 and parameters: {'n_cltr_u': 7, 'n_cltr_i': 12, 'n_epochs': 25}. Best is trial 4 with value: 0.4533136746153807.

FCP:  0.4476

[I 2024-10-23 13:08:32,055] Trial 14 finished with value: 0.4465197912997394 and parameters: {'n_cltr_u': 17, 'n_cltr_i': 13, 'n_epochs': 20}. Best is trial 4 with value: 0.4533136746153807.

FCP:  0.4465

[I 2024-10-23 13:08:52,255] Trial 15 finished with value: 0.45411870630508616 and parameters: {'n_cltr_u': 6, 'n_cltr_i': 30, 'n_epochs': 35}. Best is trial 15 with value: 0.45411870630508616.

FCP:  0.4541

[I 2024-10-23 13:09:13,090] Trial 16 finished with value: 0.4469272159416536 and parameters: {'n_cltr_u': 11, 'n_cltr_i': 30, 'n_epochs': 35}. Best is trial 15 with value: 0.45411870630508616.

FCP:  0.4469

[I 2024-10-23 13:09:34,062] Trial 17 finished with value: 0.4449903043612028 and parameters: {'n_cltr_u': 30, 'n_cltr_i': 11, 'n_epochs': 35}. Best is trial 15 with value: 0.45411870630508616.

FCP:  0.4450

[I 2024-10-23 13:09:53,962] Trial 18 finished with value: 0.4448096919605231 and parameters: {'n_cltr_u': 5, 'n_cltr_i': 30, 'n_epochs': 35}. Best is trial 15 with value: 0.45411870630508616.

FCP:  0.4448

[I 2024-10-23 13:10:01,024] Trial 19 finished with value: 0.45372080530627956 and parameters: {'n_cltr_u': 4, 'n_cltr_i': 9, 'n_epochs': 15}. Best is trial 15 with value: 0.45411870630508616.

FCP:  0.4537

[I 2024-10-23 13:10:07,938] Trial 20 finished with value: 0.45372080530627956 and parameters: {'n_cltr_u': 4, 'n_cltr_i': 9, 'n_epochs': 15}. Best is trial 15 with value: 0.45411870630508616.

FCP:  0.4537

[I 2024-10-23 13:10:15,425] Trial 21 finished with value: 0.4453259736969246 and parameters: {'n_cltr_u': 8, 'n_cltr_i': 9, 'n_epochs': 15}. Best is trial 15 with value: 0.45411870630508616.

FCP:  0.4453

[I 2024-10-23 13:10:22,275] Trial 22 finished with value: 0.45372080530627956 and parameters: {'n_cltr_u': 4, 'n_cltr_i': 9, 'n_epochs': 15}. Best is trial 15 with value: 0.45411870630508616.

FCP:  0.4537

[I 2024-10-23 13:10:29,212] Trial 23 finished with value: 0.45372080530627956 and parameters: {'n_cltr_u': 4, 'n_cltr_i': 9, 'n_epochs': 15}. Best is trial 15 with value: 0.45411870630508616.

FCP:  0.4537

[I 2024-10-23 13:10:43,746] Trial 24 finished with value: 0.45677853904869664 and parameters: {'n_cltr_u': 4, 'n_cltr_i': 8, 'n_epochs': 35}. Best is trial 24 with value: 0.45677853904869664.

FCP:  0.4568

[I 2024-10-23 13:11:02,913] Trial 25 finished with value: 0.4426658423837405 and parameters: {'n_cltr_u': 13, 'n_cltr_i': 20, 'n_epochs': 35}. Best is trial 24 with value: 0.45677853904869664.

FCP:  0.4427

[I 2024-10-23 13:11:16,274] Trial 26 finished with value: 0.45677853904869664 and parameters: {'n_cltr_u': 4, 'n_cltr_i': 8, 'n_epochs': 35}. Best is trial 24 with value: 0.45677853904869664.

FCP:  0.4568

[I 2024-10-23 13:11:29,626] Trial 27 finished with value: 0.45677853904869664 and parameters: {'n_cltr_u': 4, 'n_cltr_i': 8, 'n_epochs': 35}. Best is trial 24 with value: 0.45677853904869664.

FCP:  0.4568

[I 2024-10-23 13:11:43,512] Trial 28 finished with value: 0.45677853904869664 and parameters: {'n_cltr_u': 4, 'n_cltr_i': 8, 'n_epochs': 35}. Best is trial 24 with value: 0.45677853904869664.

FCP:  0.4568

[I 2024-10-23 13:11:59,159] Trial 29 finished with value: 0.4492649365282616 and parameters: {'n_cltr_u': 9, 'n_cltr_i': 8, 'n_epochs': 35}. Best is trial 24 with value: 0.45677853904869664.

FCP:  0.4493

[I 2024-10-23 13:12:12,500] Trial 30 finished with value: 0.45677853904869664 and parameters: {'n_cltr_u': 4, 'n_cltr_i': 8, 'n_epochs': 35}. Best is trial 24 with value: 0.45677853904869664.

FCP:  0.4568

[I 2024-10-23 13:12:25,911] Trial 31 finished with value: 0.45677853904869664 and parameters: {'n_cltr_u': 4, 'n_cltr_i': 8, 'n_epochs': 35}. Best is trial 24 with value: 0.45677853904869664.

FCP:  0.4568

[I 2024-10-23 13:12:39,650] Trial 32 finished with value: 0.45677853904869664 and parameters: {'n_cltr_u': 4, 'n_cltr_i': 8, 'n_epochs': 35}. Best is trial 24 with value: 0.45677853904869664.

FCP:  0.4568

[I 2024-10-23 13:12:57,359] Trial 33 finished with value: 0.4555633967316949 and parameters: {'n_cltr_u': 4, 'n_cltr_i': 25, 'n_epochs': 35}. Best is trial 24 with value: 0.45677853904869664.

FCP:  0.4556

[I 2024-10-23 13:13:02,644] Trial 34 finished with value: 0.44894319475270517 and parameters: {'n_cltr_u': 10, 'n_cltr_i': 4, 'n_epochs': 10}. Best is trial 24 with value: 0.45677853904869664.

FCP:  0.4489

[I 2024-10-23 13:13:15,794] Trial 35 finished with value: 0.45677853904869664 and parameters: {'n_cltr_u': 4, 'n_cltr_i': 8, 'n_epochs': 35}. Best is trial 24 with value: 0.45677853904869664.

FCP:  0.4568

[I 2024-10-23 13:13:28,486] Trial 36 finished with value: 0.4529229195392734 and parameters: {'n_cltr_u': 20, 'n_cltr_i': 8, 'n_epochs': 25}. Best is trial 24 with value: 0.45677853904869664.

FCP:  0.4529

[I 2024-10-23 13:13:43,774] Trial 37 finished with value: 0.4465633467463459 and parameters: {'n_cltr_u': 14, 'n_cltr_i': 5, 'n_epochs': 35}. Best is trial 24 with value: 0.45677853904869664.

FCP:  0.4466

[I 2024-10-23 13:13:53,956] Trial 38 finished with value: 0.44139090911261664 and parameters: {'n_cltr_u': 15, 'n_cltr_i': 8, 'n_epochs': 20}. Best is trial 24 with value: 0.45677853904869664.

FCP:  0.4414

[I 2024-10-23 13:13:59,995] Trial 39 finished with value: 0.443280164478261 and parameters: {'n_cltr_u': 17, 'n_cltr_i': 7, 'n_epochs': 10}. Best is trial 24 with value: 0.45677853904869664.

FCP:  0.4433

[I 2024-10-23 13:14:15,500] Trial 40 finished with value: 0.4545859622086407 and parameters: {'n_cltr_u': 3, 'n_cltr_i': 17, 'n_epochs': 35}. Best is trial 24 with value: 0.45677853904869664.

FCP:  0.4546

[I 2024-10-23 13:14:28,926] Trial 41 finished with value: 0.45677853904869664 and parameters: {'n_cltr_u': 4, 'n_cltr_i': 8, 'n_epochs': 35}. Best is trial 24 with value: 0.45677853904869664.

FCP:  0.4568

[I 2024-10-23 13:14:44,517] Trial 42 finished with value: 0.4567874980191049 and parameters: {'n_cltr_u': 4, 'n_cltr_i': 14, 'n_epochs': 35}. Best is trial 42 with value: 0.4567874980191049.

FCP:  0.4568

[I 2024-10-23 13:15:04,877] Trial 43 finished with value: 0.4418512297501654 and parameters: {'n_cltr_u': 25, 'n_cltr_i': 14, 'n_epochs': 35}. Best is trial 42 with value: 0.4567874980191049.

FCP:  0.4419

[I 2024-10-23 13:15:20,635] Trial 44 finished with value: 0.4448760821818153 and parameters: {'n_cltr_u': 11, 'n_cltr_i': 10, 'n_epochs': 35}. Best is trial 42 with value: 0.4567874980191049.

FCP:  0.4449

[I 2024-10-23 13:15:31,422] Trial 45 finished with value: 0.4423221602773579 and parameters: {'n_cltr_u': 7, 'n_cltr_i': 8, 'n_epochs': 25}. Best is trial 42 with value: 0.4567874980191049.

FCP:  0.4423

[I 2024-10-23 13:15:47,085] Trial 46 finished with value: 0.45201159915743283 and parameters: {'n_cltr_u': 13, 'n_cltr_i': 14, 'n_epochs': 30}. Best is trial 42 with value: 0.4567874980191049.

FCP:  0.4520

[I 2024-10-23 13:16:02,303] Trial 47 finished with value: 0.4513765678600461 and parameters: {'n_cltr_u': 5, 'n_cltr_i': 14, 'n_epochs': 35}. Best is trial 42 with value: 0.4567874980191049.

FCP:  0.4514

[I 2024-10-23 13:16:16,242] Trial 48 finished with value: 0.446639062412464 and parameters: {'n_cltr_u': 30, 'n_cltr_i': 20, 'n_epochs': 20}. Best is trial 42 with value: 0.4567874980191049.

FCP:  0.4466

[I 2024-10-23 13:16:33,451] Trial 49 finished with value: 0.44100553493192907 and parameters: {'n_cltr_u': 12, 'n_cltr_i': 13, 'n_epochs': 35}. Best is trial 42 with value: 0.4567874980191049.

FCP:  0.4410

[I 2024-10-23 13:16:38,722] Trial 50 finished with value: 0.4407328788066711 and parameters: {'n_cltr_u': 8, 'n_cltr_i': 6, 'n_epochs': 10}. Best is trial 42 with value: 0.4567874980191049.

FCP:  0.4407

[I 2024-10-23 13:16:52,207] Trial 51 finished with value: 0.45677853904869664 and parameters: {'n_cltr_u': 4, 'n_cltr_i': 8, 'n_epochs': 35}. Best is trial 42 with value: 0.4567874980191049.

FCP:  0.4568

[I 2024-10-23 13:17:06,657] Trial 52 finished with value: 0.4458046232064721 and parameters: {'n_cltr_u': 4, 'n_cltr_i': 12, 'n_epochs': 35}. Best is trial 42 with value: 0.4567874980191049.

FCP:  0.4458

[I 2024-10-23 13:17:19,028] Trial 53 finished with value: 0.45790486066146496 and parameters: {'n_cltr_u': 4, 'n_cltr_i': 3, 'n_epochs': 35}. Best is trial 53 with value: 0.45790486066146496.

FCP:  0.4579

[I 2024-10-23 13:17:32,472] Trial 54 finished with value: 0.44758399560590356 and parameters: {'n_cltr_u': 9, 'n_cltr_i': 3, 'n_epochs': 35}. Best is trial 53 with value: 0.45790486066146496.

FCP:  0.4476

[I 2024-10-23 13:17:43,839] Trial 55 finished with value: 0.4579878390236321 and parameters: {'n_cltr_u': 4, 'n_cltr_i': 3, 'n_epochs': 30}. Best is trial 55 with value: 0.4579878390236321.

FCP:  0.4580

[I 2024-10-23 13:17:55,843] Trial 56 finished with value: 0.44289751857159626 and parameters: {'n_cltr_u': 10, 'n_cltr_i': 3, 'n_epochs': 30}. Best is trial 55 with value: 0.4579878390236321.

FCP:  0.4429

[I 2024-10-23 13:18:09,316] Trial 57 finished with value: 0.4454099837230412 and parameters: {'n_cltr_u': 14, 'n_cltr_i': 3, 'n_epochs': 30}. Best is trial 55 with value: 0.4579878390236321.

FCP:  0.4454

[I 2024-10-23 13:18:21,584] Trial 58 finished with value: 0.45150295400419577 and parameters: {'n_cltr_u': 4, 'n_cltr_i': 11, 'n_epochs': 30}. Best is trial 55 with value: 0.4579878390236321.

FCP:  0.4515

[I 2024-10-23 13:18:34,741] Trial 59 finished with value: 0.4453388193625803 and parameters: {'n_cltr_u': 15, 'n_cltr_i': 3, 'n_epochs': 30}. Best is trial 55 with value: 0.4579878390236321.

FCP:  0.4453

[I 2024-10-23 13:18:49,892] Trial 60 finished with value: 0.4497270674125939 and parameters: {'n_cltr_u': 20, 'n_cltr_i': 15, 'n_epochs': 25}. Best is trial 55 with value: 0.4579878390236321.

FCP:  0.4497

[I 2024-10-23 13:19:02,298] Trial 61 finished with value: 0.449779727102507 and parameters: {'n_cltr_u': 4, 'n_cltr_i': 4, 'n_epochs': 35}. Best is trial 55 with value: 0.4579878390236321.

FCP:  0.4498

[I 2024-10-23 13:19:19,989] Trial 62 finished with value: 0.4555633967316949 and parameters: {'n_cltr_u': 4, 'n_cltr_i': 25, 'n_epochs': 35}. Best is trial 55 with value: 0.4579878390236321.

FCP:  0.4556

[I 2024-10-23 13:19:32,676] Trial 63 finished with value: 0.45790486066146496 and parameters: {'n_cltr_u': 4, 'n_cltr_i': 3, 'n_epochs': 35}. Best is trial 55 with value: 0.4579878390236321.

FCP:  0.4579

[I 2024-10-23 13:19:45,093] Trial 64 finished with value: 0.45790486066146496 and parameters: {'n_cltr_u': 4, 'n_cltr_i': 3, 'n_epochs': 35}. Best is trial 55 with value: 0.4579878390236321.

FCP:  0.4579

[I 2024-10-23 13:19:53,657] Trial 65 finished with value: 0.45359231346359735 and parameters: {'n_cltr_u': 6, 'n_cltr_i': 3, 'n_epochs': 20}. Best is trial 55 with value: 0.4579878390236321.

FCP:  0.4536

[I 2024-10-23 13:20:04,303] Trial 66 finished with value: 0.4579878390236321 and parameters: {'n_cltr_u': 4, 'n_cltr_i': 3, 'n_epochs': 30}. Best is trial 55 with value: 0.4579878390236321.

FCP:  0.4580

[I 2024-10-23 13:20:19,647] Trial 67 finished with value: 0.44805982743932393 and parameters: {'n_cltr_u': 25, 'n_cltr_i': 3, 'n_epochs': 30}. Best is trial 55 with value: 0.4579878390236321.

FCP:  0.4481

[I 2024-10-23 13:20:30,036] Trial 68 finished with value: 0.4579878390236321 and parameters: {'n_cltr_u': 4, 'n_cltr_i': 3, 'n_epochs': 30}. Best is trial 55 with value: 0.4579878390236321.

FCP:  0.4580

[I 2024-10-23 13:20:41,578] Trial 69 finished with value: 0.4485639071931161 and parameters: {'n_cltr_u': 7, 'n_cltr_i': 3, 'n_epochs': 30}. Best is trial 55 with value: 0.4579878390236321.

FCP:  0.4486

[I 2024-10-23 13:20:51,991] Trial 70 finished with value: 0.45189118476073364 and parameters: {'n_cltr_u': 3, 'n_cltr_i': 3, 'n_epochs': 30}. Best is trial 55 with value: 0.4579878390236321.

FCP:  0.4519

[I 2024-10-23 13:21:02,695] Trial 71 finished with value: 0.4579878390236321 and parameters: {'n_cltr_u': 4, 'n_cltr_i': 3, 'n_epochs': 30}. Best is trial 55 with value: 0.4579878390236321.

FCP:  0.4580

[I 2024-10-23 13:21:13,415] Trial 72 finished with value: 0.4579878390236321 and parameters: {'n_cltr_u': 4, 'n_cltr_i': 3, 'n_epochs': 30}. Best is trial 55 with value: 0.4579878390236321.

FCP:  0.4580

[I 2024-10-23 13:21:24,229] Trial 73 finished with value: 0.4579878390236321 and parameters: {'n_cltr_u': 4, 'n_cltr_i': 3, 'n_epochs': 30}. Best is trial 55 with value: 0.4579878390236321.

FCP:  0.4580

[I 2024-10-23 13:21:35,334] Trial 74 finished with value: 0.4579878390236321 and parameters: {'n_cltr_u': 4, 'n_cltr_i': 3, 'n_epochs': 30}. Best is trial 55 with value: 0.4579878390236321.

FCP:  0.4580

[I 2024-10-23 13:21:49,414] Trial 75 finished with value: 0.4487323331611543 and parameters: {'n_cltr_u': 17, 'n_cltr_i': 3, 'n_epochs': 30}. Best is trial 55 with value: 0.4579878390236321.

FCP:  0.4487

[I 2024-10-23 13:22:00,126] Trial 76 finished with value: 0.4579878390236321 and parameters: {'n_cltr_u': 4, 'n_cltr_i': 3, 'n_epochs': 30}. Best is trial 55 with value: 0.4579878390236321.

FCP:  0.4580

[I 2024-10-23 13:22:12,592] Trial 77 finished with value: 0.44899176096744553 and parameters: {'n_cltr_u': 11, 'n_cltr_i': 3, 'n_epochs': 30}. Best is trial 55 with value: 0.4579878390236321.

FCP:  0.4490

[I 2024-10-23 13:22:29,550] Trial 78 finished with value: 0.4472133713457098 and parameters: {'n_cltr_u': 30, 'n_cltr_i': 3, 'n_epochs': 30}. Best is trial 55 with value: 0.4579878390236321.

FCP:  0.4472

[I 2024-10-23 13:22:42,753] Trial 79 finished with value: 0.44279328340185986 and parameters: {'n_cltr_u': 12, 'n_cltr_i': 5, 'n_epochs': 30}. Best is trial 55 with value: 0.4579878390236321.

FCP:  0.4428

[I 2024-10-23 13:22:54,355] Trial 80 finished with value: 0.4507968294787086 and parameters: {'n_cltr_u': 4, 'n_cltr_i': 7, 'n_epochs': 30}. Best is trial 55 with value: 0.4579878390236321.

FCP:  0.4508

[I 2024-10-23 13:23:05,204] Trial 81 finished with value: 0.4579878390236321 and parameters: {'n_cltr_u': 4, 'n_cltr_i': 3, 'n_epochs': 30}. Best is trial 55 with value: 0.4579878390236321.

FCP:  0.4580

[I 2024-10-23 13:23:16,083] Trial 82 finished with value: 0.4579878390236321 and parameters: {'n_cltr_u': 4, 'n_cltr_i': 3, 'n_epochs': 30}. Best is trial 55 with value: 0.4579878390236321.

FCP:  0.4580

[I 2024-10-23 13:23:26,861] Trial 83 finished with value: 0.4579878390236321 and parameters: {'n_cltr_u': 4, 'n_cltr_i': 3, 'n_epochs': 30}. Best is trial 55 with value: 0.4579878390236321.

FCP:  0.4580

[I 2024-10-23 13:23:38,729] Trial 84 finished with value: 0.44783208376371375 and parameters: {'n_cltr_u': 8, 'n_cltr_i': 3, 'n_epochs': 30}. Best is trial 55 with value: 0.4579878390236321.

FCP:  0.4478

[I 2024-10-23 13:23:52,892] Trial 85 finished with value: 0.45289046795085336 and parameters: {'n_cltr_u': 5, 'n_cltr_i': 17, 'n_epochs': 30}. Best is trial 55 with value: 0.4579878390236321.

FCP:  0.4529

[I 2024-10-23 13:24:11,303] Trial 86 finished with value: 0.45574999018489587 and parameters: {'n_cltr_u': 13, 'n_cltr_i': 30, 'n_epochs': 30}. Best is trial 55 with value: 0.4579878390236321.

FCP:  0.4557

[I 2024-10-23 13:24:21,949] Trial 87 finished with value: 0.4579878390236321 and parameters: {'n_cltr_u': 4, 'n_cltr_i': 3, 'n_epochs': 30}. Best is trial 55 with value: 0.4579878390236321.

FCP:  0.4580

[I 2024-10-23 13:24:33,232] Trial 88 finished with value: 0.4513231198829832 and parameters: {'n_cltr_u': 4, 'n_cltr_i': 6, 'n_epochs': 30}. Best is trial 55 with value: 0.4579878390236321.

FCP:  0.4513

[I 2024-10-23 13:24:45,753] Trial 89 finished with value: 0.44896612970018185 and parameters: {'n_cltr_u': 4, 'n_cltr_i': 10, 'n_epochs': 30}. Best is trial 55 with value: 0.4579878390236321.

FCP:  0.4490

[I 2024-10-23 13:24:59,836] Trial 90 finished with value: 0.4458220083823982 and parameters: {'n_cltr_u': 9, 'n_cltr_i': 13, 'n_epochs': 30}. Best is trial 55 with value: 0.4579878390236321.

FCP:  0.4458

[I 2024-10-23 13:25:10,523] Trial 91 finished with value: 0.4579878390236321 and parameters: {'n_cltr_u': 4, 'n_cltr_i': 3, 'n_epochs': 30}. Best is trial 55 with value: 0.4579878390236321.

FCP:  0.4580

[I 2024-10-23 13:25:21,190] Trial 92 finished with value: 0.4579878390236321 and parameters: {'n_cltr_u': 4, 'n_cltr_i': 3, 'n_epochs': 30}. Best is trial 55 with value: 0.4579878390236321.

FCP:  0.4580

[I 2024-10-23 13:25:33,788] Trial 93 finished with value: 0.44829769075387826 and parameters: {'n_cltr_u': 4, 'n_cltr_i': 12, 'n_epochs': 30}. Best is trial 55 with value: 0.4579878390236321.

FCP:  0.4483

[I 2024-10-23 13:25:45,649] Trial 94 finished with value: 0.4579878390236321 and parameters: {'n_cltr_u': 4, 'n_cltr_i': 3, 'n_epochs': 30}. Best is trial 55 with value: 0.4579878390236321.

FCP:  0.4580

[I 2024-10-23 13:25:59,223] Trial 95 finished with value: 0.4428326529887156 and parameters: {'n_cltr_u': 10, 'n_cltr_i': 11, 'n_epochs': 30}. Best is trial 55 with value: 0.4579878390236321.

FCP:  0.4428

[I 2024-10-23 13:26:12,156] Trial 96 finished with value: 0.4454099837230412 and parameters: {'n_cltr_u': 14, 'n_cltr_i': 3, 'n_epochs': 30}. Best is trial 55 with value: 0.4579878390236321.

FCP:  0.4454

[I 2024-10-23 13:26:20,106] Trial 97 finished with value: 0.4521685172467653 and parameters: {'n_cltr_u': 4, 'n_cltr_i': 20, 'n_epochs': 15}. Best is trial 55 with value: 0.4579878390236321.

FCP:  0.4522

[I 2024-10-23 13:26:34,790] Trial 98 finished with value: 0.4479757115151168 and parameters: {'n_cltr_u': 20, 'n_cltr_i': 3, 'n_epochs': 30}. Best is trial 55 with value: 0.4579878390236321.

FCP:  0.4480

[I 2024-10-23 13:26:39,575] Trial 99 finished with value: 0.451180665610595 and parameters: {'n_cltr_u': 4, 'n_cltr_i': 3, 'n_epochs': 10}. Best is trial 55 with value: 0.4579878390236321.

FCP:  0.4512

In [16]:
print(stud.best_params)

{'n_cltr_u': 4, 'n_cltr_i': 3, 'n_epochs': 30}

In [17]:
best_model_surprise = CoClustering(random_state=random_state,
                                verbose=0,
                                n_cltr_u=stud.best_params['n_cltr_u'],
                                n_cltr_i=stud.best_params['n_cltr_i'],
                                n_epochs=stud.best_params['n_epochs'],
                                )

best_model_surprise.fit(trainset)


# # Производим сериализацию и записываем результат в файл формата pkl
with open(r'models\best_model_surprise.pkl', 'wb') as output:
    pickle.dump(best_model_surprise, output)

In [18]:
fig = optuna.visualization.plot_param_importances(stud)
fig.show()

In [19]:
fig = optuna.visualization.plot_contour(stud,)
fig

In [37]:
predictions = best_model_surprise.test(raw_testset)

In [38]:
precisions, recalls = surprise_precision_recall_at_k(predictions, k=3, threshold=4)

# Precision and recall can then be averaged over all users
print(sum(prec for prec in precisions.values()) / len(precisions))
print(sum(rec for rec in recalls.values()) / len(recalls))

0.0033866415804327367
0.003350152512899456